// ═══════════════════════════════════════════════════════════════════
// Lingua Franca — Constants & Language Data
// 19 target languages, 103 scenario templates, full romanization
// Ported from lingua-franca.html single-file app
// ═══════════════════════════════════════════════════════════════════

// ── Language metadata ──

export const LANG_CODES = [
  "ar","bg","zh","nl","tl","fr","de","hi","id","it","ja","ko","pl","pt","ru","es","sv","th","tr","vi"
] as const;
export type LangCode = typeof LANG_CODES[number];

export const TOTAL_LANGUAGES = LANG_CODES.length;
export const TOTAL_SCENARIOS = 103;

export const LANG_LABEL: Record<string, string> = {
  en:"English",id:"Indonesian",es:"Spanish",fr:"French",ja:"Japanese",it:"Italian",
  zh:"Chinese (Mandarin)",ko:"Korean",ar:"Arabic",hi:"Hindi",pt:"Portuguese",de:"German",
  ru:"Russian",th:"Thai",tr:"Turkish",vi:"Vietnamese",tl:"Filipino",nl:"Dutch",sv:"Swedish",pl:"Polish",bg:"Bulgarian",
  // I-speak-only languages (no learning target data)
  bn:"Bengali",ur:"Urdu",fa:"Persian",sw:"Swahili",el:"Greek",he:"Hebrew",
  ro:"Romanian",cs:"Czech",hu:"Hungarian",uk:"Ukrainian",ms:"Malay",ta:"Tamil",
  am:"Amharic",yo:"Yoruba",
};

export const LANG_FLAG: Record<string, string> = {
  en:"🇬🇧",id:"🇮🇩",es:"🇪🇸",fr:"🇫🇷",ja:"🇯🇵",it:"🇮🇹",
  zh:"🇨🇳",ko:"🇰🇷",ar:"🇸🇦",hi:"🇮🇳",pt:"🇧🇷",de:"🇩🇪",
  ru:"🇷🇺",th:"🇹🇭",tr:"🇹🇷",vi:"🇻🇳",tl:"🇵🇭",nl:"🇳🇱",sv:"🇸🇪",pl:"🇵🇱",bg:"🇧🇬",
  bn:"🇧🇩",ur:"🇵🇰",fa:"🇮🇷",sw:"🇰🇪",el:"🇬🇷",he:"🇮🇱",
  ro:"🇷🇴",cs:"🇨🇿",hu:"🇭🇺",uk:"🇺🇦",ms:"🇲🇾",ta:"🇱🇰",
  am:"🇪🇹",yo:"🇳🇬",
};

/** Native script names for the I-speak dropdown */
export const LANG_NATIVE: Record<string, string> = {
  en:"English",id:"Bahasa Indonesia",es:"Español",fr:"Français",ja:"日本語",it:"Italiano",
  zh:"中文",ko:"한국어",ar:"العربية",hi:"हिन्दी",pt:"Português",de:"Deutsch",
  ru:"Русский",th:"ภาษาไทย",tr:"Türkçe",vi:"Tiếng Việt",tl:"Filipino",nl:"Nederlands",
  sv:"Svenska",pl:"Polski",bg:"Български",
  bn:"বাংলা",ur:"اردو",fa:"فارسی",sw:"Kiswahili",el:"Ελληνικά",he:"עברית",
  ro:"Română",cs:"Čeština",hu:"Magyar",uk:"Українська",ms:"Bahasa Melayu",ta:"தமிழ்",
  am:"አማርኛ",yo:"Yorùbá",
};

/** All languages available in the "I speak" dropdown (core + extras) */
export const I_SPEAK_CODES: string[] = [
  "en","es","fr","pt","de","it","nl","sv","pl","ro","cs","hu",
  "ja","zh","ko","th","vi","ms","id","tl","ta",
  "ar","hi","ur","fa","bn","he","am",
  "ru","uk","tr","el","sw","yo","bg",
];

// ── Translated UI labels for scenario groups (keyed by I-speak lang) ──
export const UI_SCENARIO_GROUPS: Record<string, string[]> = {
  en: ["Social & Greetings","Food & Drinks","Compliments","Navigation & Help","Formal"],
  es: ["Social y Saludos","Comida y Bebidas","Cumplidos","Navegación y Ayuda","Formal"],
  fr: ["Social et Salutations","Nourriture et Boissons","Compliments","Navigation et Aide","Formel"],
  pt: ["Social e Saudações","Comida e Bebidas","Elogios","Navegação e Ajuda","Formal"],
  de: ["Soziales & Grüße","Essen & Trinken","Komplimente","Navigation & Hilfe","Formell"],
  it: ["Sociale e Saluti","Cibo e Bevande","Complimenti","Navigazione e Aiuto","Formale"],
  ja: ["社交と挨拶","食べ物と飲み物","褒め言葉","道案内とお願い","フォーマル"],
  zh: ["社交与问候","食物与饮品","赞美","导航与帮助","正式"],
  ko: ["사교 & 인사","음식 & 음료","칭찬","길 안내 & 도움","격식"],
  ar: ["اجتماعي وتحيات","طعام ومشروبات","مجاملات","توجيه ومساعدة","رسمي"],
  hi: ["सामाजिक और अभिवादन","खाना और पेय","तारीफ़","दिशा और सहायता","औपचारिक"],
  ru: ["Общение и приветствия","Еда и напитки","Комплименты","Навигация и помощь","Формальное"],
  th: ["สังคมและทักทาย","อาหารและเครื่องดื่ม","คำชม","ทิศทางและช่วยเหลือ","ทางการ"],
  tr: ["Sosyal ve Selamlaşma","Yemek ve İçecek","İltifatlar","Yön ve Yardım","Resmi"],
  id: ["Sosial & Sapaan","Makanan & Minuman","Pujian","Navigasi & Bantuan","Formal"],
  vi: ["Xã giao & Chào hỏi","Ăn uống","Lời khen","Chỉ đường & Giúp đỡ","Trang trọng"],
  pl: ["Towarzyskie & Powitania","Jedzenie & Napoje","Komplementy","Nawigacja & Pomoc","Formalnie"],
  nl: ["Sociaal & Begroetingen","Eten & Drinken","Complimenten","Navigatie & Hulp","Formeel"],
  sv: ["Socialt & Hälsningar","Mat & Dryck","Komplimanger","Navigering & Hjälp","Formellt"],
  bg: ["Социално и поздрави","Храна и напитки","Комплименти","Навигация и помощ","Официално"],
};

/** Translated phrase labels (keyed by I-speak lang → phrase key → label) */
export const UI_PHRASE_LABELS: Record<string, Record<string, string>> = {
  es: {flirty_hello:"Saludo coqueto",warm_hello:"Saludo cálido",ask_drinks:"Preguntar por bebidas",like_most:"Lo que más me gusta",smile_compliment:"Elogio de sonrisa",try_food:"Probar la comida",after_dinner:"Después de cenar",polite_help:"Pedir ayuda",where_place:"¿Dónde está...?",order_drink:"Pedir bebida",city_is:"Esta ciudad es...",formal_thanks:"Agradecimiento formal",offer_drink:"Ofrecer bebida",continue_over:"Seguir con comida",good_to_see:"Gusto en verte",food_is:"Esta comida es...",nice_to_meet:"Encantado",prefer_or:"¿Prefieres...?"},
  fr: {flirty_hello:"Salut charmeur",warm_hello:"Salut chaleureux",ask_drinks:"Demander les boissons",like_most:"Ce que j'aime le plus",smile_compliment:"Compliment sourire",try_food:"Goûter la cuisine",after_dinner:"Après le dîner",polite_help:"Demander de l'aide",where_place:"Où est...?",order_drink:"Commander un verre",city_is:"Cette ville est...",formal_thanks:"Remerciement formel",offer_drink:"Offrir un verre",continue_over:"Continuer autour d'un repas",good_to_see:"Content de te voir",food_is:"Ce plat est...",nice_to_meet:"Enchanté",prefer_or:"Tu préfères...?"},
  ja: {flirty_hello:"おしゃれな挨拶",warm_hello:"温かい挨拶",ask_drinks:"飲み物を聞く",like_most:"一番好きなもの",smile_compliment:"笑顔の褒め言葉",try_food:"料理を試す",after_dinner:"夕食後",polite_help:"助けを求める",where_place:"どこですか？",order_drink:"飲み物を注文",city_is:"この街は…",formal_thanks:"正式なお礼",offer_drink:"飲み物をすすめる",continue_over:"食事しながら続ける",good_to_see:"会えて嬉しい",food_is:"この料理は…",nice_to_meet:"はじめまして",prefer_or:"どちらが好き？"},
  zh: {flirty_hello:"俏皮问候",warm_hello:"热情问候",ask_drinks:"问饮品",like_most:"最喜欢的",smile_compliment:"微笑赞美",try_food:"尝尝美食",after_dinner:"晚餐后",polite_help:"请求帮助",where_place:"在哪里？",order_drink:"点饮料",city_is:"这座城市…",formal_thanks:"正式感谢",offer_drink:"请喝一杯",continue_over:"边吃边聊",good_to_see:"见到你真好",food_is:"这道菜…",nice_to_meet:"很高兴认识你",prefer_or:"你更喜欢？"},
  ko: {flirty_hello:"설레는 인사",warm_hello:"따뜻한 인사",ask_drinks:"음료 물어보기",like_most:"가장 좋아하는 것",smile_compliment:"미소 칭찬",try_food:"음식 맛보기",after_dinner:"저녁 식사 후",polite_help:"도움 요청",where_place:"어디예요?",order_drink:"음료 주문",city_is:"이 도시는...",formal_thanks:"격식 감사",offer_drink:"음료 권하기",continue_over:"식사하며 계속",good_to_see:"만나서 반가워",food_is:"이 음식은...",nice_to_meet:"만나서 반갑습니다",prefer_or:"뭐가 좋아?"},
  de: {flirty_hello:"Flirtender Gruß",warm_hello:"Herzlicher Gruß",ask_drinks:"Nach Getränken fragen",like_most:"Was ich am liebsten mag",smile_compliment:"Lächeln-Kompliment",try_food:"Essen probieren",after_dinner:"Nach dem Abendessen",polite_help:"Um Hilfe bitten",where_place:"Wo ist...?",order_drink:"Getränk bestellen",city_is:"Diese Stadt ist...",formal_thanks:"Formeller Dank",offer_drink:"Getränk anbieten",continue_over:"Weiter beim Essen",good_to_see:"Schön dich zu sehen",food_is:"Dieses Essen ist...",nice_to_meet:"Freut mich",prefer_or:"Was bevorzugst du?"},
  pt: {flirty_hello:"Olá charmoso",warm_hello:"Olá caloroso",ask_drinks:"Perguntar sobre bebidas",like_most:"O que mais gosto",smile_compliment:"Elogio do sorriso",try_food:"Experimentar a comida",after_dinner:"Depois do jantar",polite_help:"Pedir ajuda",where_place:"Onde fica...?",order_drink:"Pedir bebida",city_is:"Esta cidade é...",formal_thanks:"Agradecimento formal",offer_drink:"Oferecer bebida",continue_over:"Continuar comendo",good_to_see:"Bom te ver",food_is:"Esta comida é...",nice_to_meet:"Prazer em conhecer",prefer_or:"Você prefere...?"},
  ar: {flirty_hello:"تحية لطيفة",warm_hello:"تحية دافئة",ask_drinks:"سؤال عن المشروبات",like_most:"ما أحبه أكثر",smile_compliment:"مجاملة الابتسامة",try_food:"تجربة الطعام",after_dinner:"بعد العشاء",polite_help:"طلب المساعدة",where_place:"أين يقع...؟",order_drink:"طلب مشروب",city_is:"هذه المدينة...",formal_thanks:"شكر رسمي",offer_drink:"عرض مشروب",continue_over:"نكمل على الطعام",good_to_see:"سعيد برؤيتك",food_is:"هذا الطعام...",nice_to_meet:"تشرفنا",prefer_or:"تفضل أم...؟"},
  hi: {flirty_hello:"मज़ेदार नमस्ते",warm_hello:"गर्मजोशी भरा नमस्ते",ask_drinks:"पेय के बारे में पूछें",like_most:"मुझे सबसे ज़्यादा पसंद",smile_compliment:"मुस्कान की तारीफ़",try_food:"खाना चखें",after_dinner:"खाने के बाद",polite_help:"मदद माँगें",where_place:"कहाँ है...?",order_drink:"पेय ऑर्डर करें",city_is:"यह शहर है...",formal_thanks:"औपचारिक धन्यवाद",offer_drink:"पेय पेश करें",continue_over:"खाते हुए आगे बढ़ें",good_to_see:"आपसे मिलकर अच्छा लगा",food_is:"यह खाना है...",nice_to_meet:"आपसे मिलकर ख़ुशी हुई",prefer_or:"आप क्या पसंद करेंगे?"},
  ru: {flirty_hello:"Кокетливое приветствие",warm_hello:"Тёплое приветствие",ask_drinks:"Спросить о напитках",like_most:"Что мне нравится больше всего",smile_compliment:"Комплимент улыбке",try_food:"Попробовать еду",after_dinner:"После ужина",polite_help:"Попросить помощь",where_place:"Где находится...?",order_drink:"Заказать напиток",city_is:"Этот город...",formal_thanks:"Формальная благодарность",offer_drink:"Предложить напиток",continue_over:"Продолжить за едой",good_to_see:"Рад тебя видеть",food_is:"Эта еда...",nice_to_meet:"Приятно познакомиться",prefer_or:"Что предпочитаете?"},
  id: {flirty_hello:"Sapaan menggoda",warm_hello:"Sapaan hangat",ask_drinks:"Tanya minuman",like_most:"Yang paling saya suka",smile_compliment:"Pujian senyuman",try_food:"Coba makanannya",after_dinner:"Setelah makan malam",polite_help:"Minta bantuan",where_place:"Di mana...?",order_drink:"Pesan minuman",city_is:"Kota ini...",formal_thanks:"Terima kasih formal",offer_drink:"Tawarkan minuman",continue_over:"Lanjut sambil makan",good_to_see:"Senang bertemu",food_is:"Makanan ini...",nice_to_meet:"Senang berkenalan",prefer_or:"Lebih suka...?"},
  th: {flirty_hello:"ทักทายหวานๆ",warm_hello:"ทักทายอบอุ่น",ask_drinks:"ถามเรื่องเครื่องดื่ม",like_most:"สิ่งที่ชอบที่สุด",smile_compliment:"ชมรอยยิ้ม",try_food:"ลองอาหาร",after_dinner:"หลังอาหารเย็น",polite_help:"ขอความช่วยเหลือ",where_place:"อยู่ที่ไหน?",order_drink:"สั่งเครื่องดื่ม",city_is:"เมืองนี้...",formal_thanks:"ขอบคุณอย่างเป็นทางการ",offer_drink:"เสนอเครื่องดื่ม",continue_over:"คุยต่อระหว่างกิน",good_to_see:"ดีใจที่ได้เจอ",food_is:"อาหารนี้...",nice_to_meet:"ยินดีที่ได้พบ",prefer_or:"ชอบอะไรมากกว่า?"},
  tr: {flirty_hello:"Çekici selam",warm_hello:"Sıcak selam",ask_drinks:"İçecek sormak",like_most:"En sevdiğim",smile_compliment:"Gülümseme iltifatı",try_food:"Yemeği dene",after_dinner:"Akşam yemeğinden sonra",polite_help:"Yardım istemek",where_place:"Nerede...?",order_drink:"İçecek sipariş et",city_is:"Bu şehir...",formal_thanks:"Resmi teşekkür",offer_drink:"İçecek ikram et",continue_over:"Yemekte devam et",good_to_see:"Seni görmek güzel",food_is:"Bu yemek...",nice_to_meet:"Tanıştığıma memnunum",prefer_or:"Hangisini tercih edersin?"},
  vi: {flirty_hello:"Chào hỏi duyên dáng",warm_hello:"Chào ấm áp",ask_drinks:"Hỏi về đồ uống",like_most:"Thích nhất",smile_compliment:"Khen nụ cười",try_food:"Thử món ăn",after_dinner:"Sau bữa tối",polite_help:"Xin giúp đỡ",where_place:"Ở đâu...?",order_drink:"Gọi đồ uống",city_is:"Thành phố này...",formal_thanks:"Cảm ơn trang trọng",offer_drink:"Mời đồ uống",continue_over:"Tiếp tục bên bàn ăn",good_to_see:"Vui được gặp bạn",food_is:"Món này...",nice_to_meet:"Hân hạnh",prefer_or:"Bạn thích gì hơn?"},
  bg: {flirty_hello:"Кокетен поздрав",warm_hello:"Топъл поздрав",ask_drinks:"Питане за напитки",like_most:"Какво харесвам най-много",smile_compliment:"Комплимент за усмивка",try_food:"Опитай храната",after_dinner:"След вечеря",polite_help:"Моля за помощ",where_place:"Къде е...?",order_drink:"Поръчай напитка",city_is:"Този град е...",formal_thanks:"Официална благодарност",offer_drink:"Предложи напитка",continue_over:"Продължи с храна",good_to_see:"Радвам се да те видя",food_is:"Тази храна е...",nice_to_meet:"Приятно ми е",prefer_or:"Предпочиташ...?"},
};

/** Get translated scenario group label */
export function uiGroupLabel(speakLang: string, groupIdx: number, fallback: string): string {
  return UI_SCENARIO_GROUPS[speakLang]?.[groupIdx] ?? fallback;
}

/** Get translated phrase label */
export function uiPhraseLabel(speakLang: string, key: string, fallback: string): string {
  return UI_PHRASE_LABELS[speakLang]?.[key] ?? fallback;
}

export const NEEDS_ROM: Record<string, boolean> = {
  ja: true, zh: true, ko: true, ar: true, hi: true, ru: true, th: true, bg: true
};

/** All languages benefit from phonetic guides */
export function needsPhon(_lang: string): boolean {
  return true;
}

export function needsRom(lang: string): boolean {
  return !!NEEDS_ROM[lang];
}

// ── Per-language culture data ──

export interface CultureData {
  dem: string;
  dems: string;
  cities: string[];
  venues: string[];
  foods: string[];
  drinks: string[];
}

export const CULTURE: Record<string, CultureData> = {
  id:{dem:"Indonesian",dems:"an Indonesian",cities:["Jakarta","Bali","Yogyakarta","Bandung","Surabaya"],venues:["warung","angkringan","nasi padang place"],foods:["nasi goreng","satay","rendang","gado-gado"],drinks:["es teh","kopi tubruk","jamu"]},
  es:{dem:"Spanish",dems:"a Spanish",cities:["Madrid","Barcelona","Mexico City","Buenos Aires","Seville"],venues:["tapas bar","taquería","bodega"],foods:["paella","tacos","churros","empanadas"],drinks:["sangría","horchata","tinto de verano"]},
  fr:{dem:"French",dems:"a French",cities:["Paris","Lyon","Nice","Marseille","Bordeaux"],venues:["bistro","brasserie","cave à vin"],foods:["croissants","crêpes","coq au vin","escargot"],drinks:["vin rouge","pastis","café crème"]},
  ja:{dem:"Japanese",dems:"a Japanese",cities:["Tokyo","Kyoto","Osaka","Shibuya","Shinjuku"],venues:["izakaya","ramen shop","onsen"],foods:["sushi","ramen","okonomiyaki","tempura"],drinks:["sake","matcha","shōchū"]},
  it:{dem:"Italian",dems:"an Italian",cities:["Rome","Milan","Florence","Naples","Venice"],venues:["trattoria","enoteca","gelateria"],foods:["pasta","risotto","gelato","bruschetta"],drinks:["espresso","Aperol spritz","limoncello"]},
  zh:{dem:"Chinese",dems:"a Chinese",cities:["Beijing","Shanghai","Chengdu","Guangzhou","Shenzhen"],venues:["hot pot place","dumpling house","tea house"],foods:["dim sum","hot pot","jiānbǐng","Peking duck"],drinks:["báijiǔ","bubble tea","oolong tea"]},
  ko:{dem:"Korean",dems:"a Korean",cities:["Seoul","Busan","Jeju","Gangnam","Itaewon"],venues:["samgyeopsal spot","pojangmacha","noraebang"],foods:["bibimbap","kimchi jjigae","tteokbokki","bulgogi"],drinks:["soju","makgeolli","banana milk"]},
  ar:{dem:"Arabic",dems:"an Arabic",cities:["Dubai","Cairo","Marrakech","Riyadh","Amman"],venues:["shisha lounge","souk café","rooftop majlis"],foods:["hummus","falafel","shawarma","mansaf"],drinks:["Arabic coffee","mint tea","jallab"]},
  hi:{dem:"Hindi",dems:"an Indian",cities:["Mumbai","Delhi","Jaipur","Bangalore","Goa"],venues:["dhaba","chai stall","rooftop restaurant"],foods:["biryani","dosa","butter chicken","chaat"],drinks:["masala chai","lassi","nimbu pani"]},
  pt:{dem:"Portuguese",dems:"a Brazilian",cities:["São Paulo","Lisbon","Rio de Janeiro","Porto","Brasília"],venues:["churrascaria","padaria","boteco"],foods:["feijoada","pastéis de nata","pão de queijo","coxinha"],drinks:["caipirinha","açaí","cafezinho"]},
  de:{dem:"German",dems:"a German",cities:["Berlin","Munich","Hamburg","Frankfurt","Vienna"],venues:["biergarten","kneipe","weinstube"],foods:["schnitzel","bratwurst","pretzel","käsespätzle"],drinks:["Weißbier","Glühwein","Apfelschorle"]},
  ru:{dem:"Russian",dems:"a Russian",cities:["Moscow","St. Petersburg","Kazan","Sochi","Novosibirsk"],venues:["stolovaya","tea room","banya nearby"],foods:["borscht","pelmeni","blini","beef stroganoff"],drinks:["kvass","kompot","Russian tea"]},
  th:{dem:"Thai",dems:"a Thai",cities:["Bangkok","Chiang Mai","Phuket","Pattaya","Krabi"],venues:["street stall","rooftop bar","night bazaar"],foods:["pad thai","som tam","mango sticky rice","tom yum"],drinks:["Thai iced tea","Chang beer","coconut water"]},
  tr:{dem:"Turkish",dems:"a Turkish",cities:["Istanbul","Ankara","Izmir","Cappadocia","Antalya"],venues:["meyhane","kebab shop","çay bahçesi"],foods:["kebab","baklava","pide","lahmacun"],drinks:["Turkish tea","ayran","Turkish coffee"]},
  vi:{dem:"Vietnamese",dems:"a Vietnamese",cities:["Hanoi","Ho Chi Minh City","Da Nang","Hoi An","Nha Trang"],venues:["phở shop","bún chả spot","bia hoi corner"],foods:["phở","bánh mì","bún chả","gỏi cuốn"],drinks:["cà phê sữa đá","bia hơi","sinh tố"]},
  tl:{dem:"Filipino",dems:"a Filipino",cities:["Manila","Cebu","Boracay","Davao","Palawan"],venues:["carinderia","karaoke bar","ihawan"],foods:["adobo","sinigang","halo-halo","lechon"],drinks:["San Miguel","calamansi juice","tuba"]},
  nl:{dem:"Dutch",dems:"a Dutch",cities:["Amsterdam","Rotterdam","Utrecht","The Hague","Delft"],venues:["brown café","borrel spot","pannenkoeken house"],foods:["bitterballen","stroopwafel","stamppot","herring"],drinks:["Heineken","jenever","koffie verkeerd"]},
  sv:{dem:"Swedish",dems:"a Swedish",cities:["Stockholm","Gothenburg","Malmö","Uppsala","Visby"],venues:["fika café","smörgåsbord hall","gastropub"],foods:["meatballs","kanelbullar","gravlax","toast skagen"],drinks:["glögg","snaps","Swedish coffee"]},
  pl:{dem:"Polish",dems:"a Polish",cities:["Warsaw","Krakow","Gdańsk","Wrocław","Poznań"],venues:["milk bar","vodka bar","pierogi spot"],foods:["pierogi","żurek","bigos","placki ziemniaczane"],drinks:["żubrówka","kompot","Polish mead"]}
};

// ── Vocabulary items per language ──

export interface VocabItem {
  en: string;
  tr: string;
  rom?: string;
  phon?: string;
  custom?: boolean;
}

export type VocabCategory = "DRINKS" | "FOOD" | "DESSERT" | "ADJ_TASTE" | "GREETING" | "COMPLIMENT" | "PLACE";

export const VOCAB_CATEGORIES: VocabCategory[] = ["DRINKS","FOOD","DESSERT","ADJ_TASTE","GREETING","COMPLIMENT","PLACE"];

export const VOCAB: Record<string, Record<VocabCategory, VocabItem[]>> = {
  id:{DRINKS:[{en:"beer",tr:"bir"},{en:"wine",tr:"anggur"},{en:"cocktail",tr:"koktail"},{en:"coffee",tr:"kopi"},{en:"tea",tr:"teh"},{en:"juice",tr:"jus"},{en:"whiskey",tr:"wiski"},{en:"water",tr:"air"}],FOOD:[{en:"pasta",tr:"pasta"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"salad"},{en:"steak",tr:"steik"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"burger"},{en:"soup",tr:"sup"},{en:"rice",tr:"nasi"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"gelato"},{en:"cheesecake",tr:"kue keju"},{en:"chocolate",tr:"cokelat"},{en:"cake",tr:"kue"},{en:"cookies",tr:"kukis"}],ADJ_TASTE:[{en:"refreshing",tr:"menyegarkan"},{en:"rich",tr:"kaya rasa"},{en:"light",tr:"ringan"},{en:"bitter",tr:"pahit"},{en:"sweet",tr:"manis"},{en:"spicy",tr:"pedas"},{en:"delicious",tr:"enak"}],GREETING:[{en:"Hi",tr:"Hai"},{en:"Hello",tr:"Halo"},{en:"Hey there",tr:"Hei"},{en:"Good evening",tr:"Selamat malam"},{en:"Welcome",tr:"Selamat datang"}],COMPLIMENT:[{en:"beautiful",tr:"cantik"},{en:"lovely",tr:"manis"},{en:"stunning",tr:"menawan"},{en:"charming",tr:"mempesona"},{en:"elegant",tr:"elegan"},{en:"radiant",tr:"berseri"}],PLACE:[{en:"restaurant",tr:"restoran"},{en:"cafe",tr:"kafe"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hotel"},{en:"market",tr:"pasar"},{en:"station",tr:"stasiun"}]},
  es:{DRINKS:[{en:"beer",tr:"cerveza"},{en:"wine",tr:"vino"},{en:"cocktail",tr:"cóctel"},{en:"coffee",tr:"café"},{en:"tea",tr:"té"},{en:"juice",tr:"jugo"},{en:"whiskey",tr:"whisky"},{en:"water",tr:"agua"}],FOOD:[{en:"pasta",tr:"pasta"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"ensalada"},{en:"steak",tr:"bistec"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"hamburguesa"},{en:"soup",tr:"sopa"},{en:"rice",tr:"arroz"}],DESSERT:[{en:"tiramisu",tr:"tiramisú"},{en:"gelato",tr:"helado"},{en:"cheesecake",tr:"tarta de queso"},{en:"chocolate",tr:"chocolate"},{en:"cake",tr:"pastel"},{en:"cookies",tr:"galletas"}],ADJ_TASTE:[{en:"refreshing",tr:"refrescante"},{en:"rich",tr:"sabroso"},{en:"light",tr:"ligero"},{en:"bitter",tr:"amargo"},{en:"sweet",tr:"dulce"},{en:"spicy",tr:"picante"},{en:"delicious",tr:"delicioso"}],GREETING:[{en:"Hi",tr:"Hola"},{en:"Hello",tr:"Buenas"},{en:"Hey there",tr:"Qué tal"},{en:"Good evening",tr:"Buenas noches"},{en:"Welcome",tr:"Bienvenido"}],COMPLIMENT:[{en:"beautiful",tr:"hermosa"},{en:"lovely",tr:"encantadora"},{en:"stunning",tr:"preciosa"},{en:"charming",tr:"encantador"},{en:"elegant",tr:"elegante"},{en:"radiant",tr:"radiante"}],PLACE:[{en:"restaurant",tr:"restaurante"},{en:"cafe",tr:"cafetería"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hotel"},{en:"market",tr:"mercado"},{en:"station",tr:"estación"}]},
  fr:{DRINKS:[{en:"beer",tr:"bière"},{en:"wine",tr:"vin"},{en:"cocktail",tr:"cocktail"},{en:"coffee",tr:"café"},{en:"tea",tr:"thé"},{en:"juice",tr:"jus"},{en:"whiskey",tr:"whisky"},{en:"water",tr:"eau"}],FOOD:[{en:"pasta",tr:"pâtes"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"salade"},{en:"steak",tr:"steak"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"burger"},{en:"soup",tr:"soupe"},{en:"rice",tr:"riz"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"glace"},{en:"cheesecake",tr:"cheesecake"},{en:"chocolate",tr:"chocolat"},{en:"cake",tr:"gâteau"},{en:"cookies",tr:"biscuits"}],ADJ_TASTE:[{en:"refreshing",tr:"rafraîchissant"},{en:"rich",tr:"riche"},{en:"light",tr:"léger"},{en:"bitter",tr:"amer"},{en:"sweet",tr:"doux"},{en:"spicy",tr:"épicé"},{en:"delicious",tr:"délicieux"}],GREETING:[{en:"Hi",tr:"Salut"},{en:"Hello",tr:"Bonjour"},{en:"Hey there",tr:"Coucou"},{en:"Good evening",tr:"Bonsoir"},{en:"Welcome",tr:"Bienvenue"}],COMPLIMENT:[{en:"beautiful",tr:"belle"},{en:"lovely",tr:"charmante"},{en:"stunning",tr:"magnifique"},{en:"charming",tr:"charmant"},{en:"elegant",tr:"élégant"},{en:"radiant",tr:"rayonnant"}],PLACE:[{en:"restaurant",tr:"restaurant"},{en:"cafe",tr:"café"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hôtel"},{en:"market",tr:"marché"},{en:"station",tr:"gare"}]},
  ja:{DRINKS:[{en:"beer",tr:"ビール",rom:"biiru",phon:"bee·ru"},{en:"wine",tr:"ワイン",rom:"wain",phon:"wah·een"},{en:"cocktail",tr:"カクテル",rom:"kakuteru",phon:"kah·koo·teh·ru"},{en:"coffee",tr:"コーヒー",rom:"koohii",phon:"koh·hee"},{en:"tea",tr:"お茶",rom:"ocha",phon:"oh·chah"},{en:"juice",tr:"ジュース",rom:"juusu",phon:"joo·su"},{en:"whiskey",tr:"ウイスキー",rom:"uisukii",phon:"oo·ee·su·kee"},{en:"water",tr:"水",rom:"mizu",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"パスタ",rom:"pasuta",phon:"pah·su·tah"},{en:"pizza",tr:"ピザ",rom:"piza",phon:"pee·zah"},{en:"salad",tr:"サラダ",rom:"sarada",phon:"sah·rah·dah"},{en:"steak",tr:"ステーキ",rom:"suteeki",phon:"su·teh·kee"},{en:"sushi",tr:"寿司",rom:"sushi",phon:"soo·shee"},{en:"burger",tr:"ハンバーガー",rom:"hanbaagaa",phon:"hahn·bah·gah"},{en:"soup",tr:"スープ",rom:"suupu",phon:"soo·pu"},{en:"rice",tr:"ご飯",rom:"gohan",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"ティラミス",rom:"tiramisu",phon:"tee·rah·mee·su"},{en:"gelato",tr:"ジェラート",rom:"jeraato",phon:"jeh·rah·toh"},{en:"cheesecake",tr:"チーズケーキ",rom:"chiizukeeki",phon:"chee·zu·keh·kee"},{en:"chocolate",tr:"チョコレート",rom:"chokoréto",phon:"choh·koh·reh·toh"},{en:"cake",tr:"ケーキ",rom:"keeki",phon:"keh·kee"},{en:"cookies",tr:"クッキー",rom:"kukkii",phon:"koo·kee"}],ADJ_TASTE:[{en:"refreshing",tr:"さっぱり",rom:"sappari",phon:"sahp·pah·ree"},{en:"rich",tr:"濃厚",rom:"noukō",phon:"noh·koh"},{en:"light",tr:"軽い",rom:"karui",phon:"kah·roo·ee"},{en:"bitter",tr:"苦い",rom:"nigai",phon:"nee·gah·ee"},{en:"sweet",tr:"甘い",rom:"amai",phon:"ah·mah·ee"},{en:"spicy",tr:"辛い",rom:"karai",phon:"kah·rah·ee"},{en:"delicious",tr:"美味しい",rom:"oishii",phon:"oh·ee·shee"}],GREETING:[{en:"Hi",tr:"やあ",rom:"yaa",phon:"yah"},{en:"Hello",tr:"こんにちは",rom:"konnichiwa",phon:"kohn·nee·chee·wah"},{en:"Hey there",tr:"どうも",rom:"doumo",phon:"doh·moh"},{en:"Good evening",tr:"こんばんは",rom:"konbanwa",phon:"kohn·bahn·wah"},{en:"Welcome",tr:"ようこそ",rom:"youkoso",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"きれい",rom:"kirei",phon:"kee·reh·ee"},{en:"lovely",tr:"素敵",rom:"suteki",phon:"su·teh·kee"},{en:"stunning",tr:"見とれる",rom:"mitoreru",phon:"mee·toh·reh·ru"},{en:"charming",tr:"魅力的",rom:"miryokuteki",phon:"mee·ryoh·ku·teh·kee"},{en:"elegant",tr:"上品",rom:"jouhin",phon:"joh·heen"},{en:"radiant",tr:"輝く",rom:"kagayaku",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"レストラン",rom:"resutoran",phon:"reh·su·toh·rahn"},{en:"cafe",tr:"カフェ",rom:"kafe",phon:"kah·feh"},{en:"bar",tr:"バー",rom:"baa",phon:"bah"},{en:"hotel",tr:"ホテル",rom:"hoteru",phon:"hoh·teh·ru"},{en:"market",tr:"市場",rom:"ichiba",phon:"ee·chee·bah"},{en:"station",tr:"駅",rom:"eki",phon:"eh·kee"}]},
  it:{DRINKS:[{en:"beer",tr:"birra"},{en:"wine",tr:"vino"},{en:"cocktail",tr:"cocktail"},{en:"coffee",tr:"caffè"},{en:"tea",tr:"tè"},{en:"juice",tr:"succo"},{en:"whiskey",tr:"whisky"},{en:"water",tr:"acqua"}],FOOD:[{en:"pasta",tr:"pasta"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"insalata"},{en:"steak",tr:"bistecca"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"hamburger"},{en:"soup",tr:"zuppa"},{en:"rice",tr:"riso"}],DESSERT:[{en:"tiramisu",tr:"tiramisù"},{en:"gelato",tr:"gelato"},{en:"cheesecake",tr:"cheesecake"},{en:"chocolate",tr:"cioccolato"},{en:"cake",tr:"torta"},{en:"cookies",tr:"biscotti"}],ADJ_TASTE:[{en:"refreshing",tr:"rinfrescante"},{en:"rich",tr:"ricco"},{en:"light",tr:"leggero"},{en:"bitter",tr:"amaro"},{en:"sweet",tr:"dolce"},{en:"spicy",tr:"piccante"},{en:"delicious",tr:"delizioso"}],GREETING:[{en:"Hi",tr:"Ciao"},{en:"Hello",tr:"Salve"},{en:"Hey there",tr:"Ehi"},{en:"Good evening",tr:"Buonasera"},{en:"Welcome",tr:"Benvenuto"}],COMPLIMENT:[{en:"beautiful",tr:"bella"},{en:"lovely",tr:"adorabile"},{en:"stunning",tr:"stupenda"},{en:"charming",tr:"affascinante"},{en:"elegant",tr:"elegante"},{en:"radiant",tr:"raggiante"}],PLACE:[{en:"restaurant",tr:"ristorante"},{en:"cafe",tr:"caffetteria"},{en:"bar",tr:"bar"},{en:"hotel",tr:"albergo"},{en:"market",tr:"mercato"},{en:"station",tr:"stazione"}]},
  zh:{DRINKS:[{en:"beer",tr:"啤酒",rom:"píjiǔ",phon:"bee·ru"},{en:"wine",tr:"葡萄酒",rom:"pútáojiǔ",phon:"wah·een"},{en:"cocktail",tr:"鸡尾酒",rom:"jīwěijiǔ",phon:"kah·koo·teh·ru"},{en:"coffee",tr:"咖啡",rom:"kāfēi",phon:"koh·hee"},{en:"tea",tr:"茶",rom:"chá",phon:"oh·chah"},{en:"juice",tr:"果汁",rom:"guǒzhī",phon:"joo·su"},{en:"whiskey",tr:"威士忌",rom:"wēishìjì",phon:"oo·ee·su·kee"},{en:"water",tr:"水",rom:"shuǐ",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"意大利面",rom:"yìdàlì miàn",phon:"pah·su·tah"},{en:"pizza",tr:"披萨",rom:"pīsà",phon:"pee·zah"},{en:"salad",tr:"沙拉",rom:"shālā",phon:"sah·rah·dah"},{en:"steak",tr:"牛排",rom:"niúpái",phon:"su·teh·kee"},{en:"sushi",tr:"寿司",rom:"shòusī",phon:"soo·shee"},{en:"burger",tr:"汉堡",rom:"hànbǎo",phon:"hahn·bah·gah"},{en:"soup",tr:"汤",rom:"tāng",phon:"soo·pu"},{en:"rice",tr:"米饭",rom:"mǐfàn",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"提拉米苏",rom:"tílāmǐsū",phon:"tee·rah·mee·su"},{en:"gelato",tr:"冰淇淋",rom:"bīngqílín",phon:"jeh·rah·toh"},{en:"cheesecake",tr:"芝士蛋糕",rom:"zhīshì dàngāo",phon:"chee·zu·keh·kee"},{en:"chocolate",tr:"巧克力",rom:"qiǎokèlì",phon:"choh·koh·reh·toh"},{en:"cake",tr:"蛋糕",rom:"dàngāo",phon:"keh·kee"},{en:"cookies",tr:"饼干",rom:"bǐnggān",phon:"koo·kee"}],ADJ_TASTE:[{en:"refreshing",tr:"清爽",rom:"qīngshuǎng",phon:"sahp·pah·ree"},{en:"rich",tr:"浓郁",rom:"nóngyù",phon:"noh·koh"},{en:"light",tr:"清淡",rom:"qīngdàn",phon:"kah·roo·ee"},{en:"bitter",tr:"苦",rom:"kǔ",phon:"nee·gah·ee"},{en:"sweet",tr:"甜",rom:"tián",phon:"ah·mah·ee"},{en:"spicy",tr:"辣",rom:"là",phon:"kah·rah·ee"},{en:"delicious",tr:"好吃",rom:"hǎochī",phon:"oh·ee·shee"}],GREETING:[{en:"Hi",tr:"你好",rom:"nǐ hǎo",phon:"yah"},{en:"Hello",tr:"您好",rom:"nín hǎo",phon:"kohn·nee·chee·wah"},{en:"Hey there",tr:"嘿",rom:"hēi",phon:"doh·moh"},{en:"Good evening",tr:"晚上好",rom:"wǎnshàng hǎo",phon:"kohn·bahn·wah"},{en:"Welcome",tr:"欢迎",rom:"huānyíng",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"漂亮",rom:"piàoliang",phon:"kee·reh·ee"},{en:"lovely",tr:"可爱",rom:"kě'ài",phon:"su·teh·kee"},{en:"stunning",tr:"惊艳",rom:"jīngyàn",phon:"mee·toh·reh·ru"},{en:"charming",tr:"迷人",rom:"mírén",phon:"mee·ryoh·ku·teh·kee"},{en:"elegant",tr:"优雅",rom:"yōuyǎ",phon:"joh·heen"},{en:"radiant",tr:"容光焕发",rom:"róngguāng huànfā",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"餐厅",rom:"cāntīng",phon:"reh·su·toh·rahn"},{en:"cafe",tr:"咖啡厅",rom:"kāfēi tīng",phon:"kah·feh"},{en:"bar",tr:"酒吧",rom:"jiǔbā",phon:"bah"},{en:"hotel",tr:"酒店",rom:"jiǔdiàn",phon:"hoh·teh·ru"},{en:"market",tr:"市场",rom:"shìchǎng",phon:"ee·chee·bah"},{en:"station",tr:"车站",rom:"chēzhàn",phon:"eh·kee"}]},
  ko:{DRINKS:[{en:"beer",tr:"맥주",rom:"maekju",phon:"bee·ru"},{en:"wine",tr:"와인",rom:"wain",phon:"wah·een"},{en:"cocktail",tr:"칵테일",rom:"kakteil",phon:"kah·koo·teh·ru"},{en:"coffee",tr:"커피",rom:"keopi",phon:"koh·hee"},{en:"tea",tr:"차",rom:"cha",phon:"oh·chah"},{en:"juice",tr:"주스",rom:"juseu",phon:"joo·su"},{en:"whiskey",tr:"위스키",rom:"wiseuki",phon:"oo·ee·su·kee"},{en:"water",tr:"물",rom:"mul",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"파스타",rom:"paseuta",phon:"pah·su·tah"},{en:"pizza",tr:"피자",rom:"pija",phon:"pee·zah"},{en:"salad",tr:"샐러드",rom:"saelleodeu",phon:"sah·rah·dah"},{en:"steak",tr:"스테이크",rom:"seuteikeu",phon:"su·teh·kee"},{en:"sushi",tr:"초밥",rom:"chobap",phon:"soo·shee"},{en:"burger",tr:"버거",rom:"beogeo",phon:"hahn·bah·gah"},{en:"soup",tr:"국",rom:"guk",phon:"soo·pu"},{en:"rice",tr:"밥",rom:"bap",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"티라미수",rom:"tiramisu",phon:"tee·rah·mee·su"},{en:"gelato",tr:"젤라토",rom:"jellato",phon:"jeh·rah·toh"},{en:"cheesecake",tr:"치즈케익",rom:"chijeukeiik",phon:"chee·zu·keh·kee"},{en:"chocolate",tr:"초콜릿",rom:"chokollit",phon:"choh·koh·reh·toh"},{en:"cake",tr:"케이크",rom:"keikeu",phon:"keh·kee"},{en:"cookies",tr:"쿠키",rom:"kuki",phon:"koo·kee"}],ADJ_TASTE:[{en:"refreshing",tr:"상쾌한",rom:"sangkwaehan",phon:"sahp·pah·ree"},{en:"rich",tr:"풍부한",rom:"pungbuhan",phon:"noh·koh"},{en:"light",tr:"가벼운",rom:"gabyeoun",phon:"kah·roo·ee"},{en:"bitter",tr:"쓴",rom:"ssun",phon:"nee·gah·ee"},{en:"sweet",tr:"달콤한",rom:"dalkomhan",phon:"ah·mah·ee"},{en:"spicy",tr:"매운",rom:"maeun",phon:"kah·rah·ee"},{en:"delicious",tr:"맛있는",rom:"masinneun",phon:"oh·ee·shee"}],GREETING:[{en:"Hi",tr:"안녕",rom:"annyeong",phon:"yah"},{en:"Hello",tr:"안녕하세요",rom:"annyeonghaseyo",phon:"kohn·nee·chee·wah"},{en:"Hey there",tr:"여기요",rom:"yeogiyo",phon:"doh·moh"},{en:"Good evening",tr:"좋은 저녁",rom:"joeun jeonyeok",phon:"kohn·bahn·wah"},{en:"Welcome",tr:"환영합니다",rom:"hwanyeonghamnida",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"예쁜",rom:"yeppeun",phon:"kee·reh·ee"},{en:"lovely",tr:"사랑스러운",rom:"sarangseureoun",phon:"su·teh·kee"},{en:"stunning",tr:"눈부신",rom:"nunbusin",phon:"mee·toh·reh·ru"},{en:"charming",tr:"매력적인",rom:"maeryeokjeogin",phon:"mee·ryoh·ku·teh·kee"},{en:"elegant",tr:"우아한",rom:"uahan",phon:"joh·heen"},{en:"radiant",tr:"빛나는",rom:"binnaneun",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"식당",rom:"sikdang",phon:"reh·su·toh·rahn"},{en:"cafe",tr:"카페",rom:"kape",phon:"kah·feh"},{en:"bar",tr:"바",rom:"ba",phon:"bah"},{en:"hotel",tr:"호텔",rom:"hotel",phon:"hoh·teh·ru"},{en:"market",tr:"시장",rom:"sijang",phon:"ee·chee·bah"},{en:"station",tr:"역",rom:"yeok",phon:"eh·kee"}]},
  ar:{DRINKS:[{en:"beer",tr:"بيرة",rom:"biira",phon:"bee·ru"},{en:"wine",tr:"نبيذ",rom:"nabiidh",phon:"wah·een"},{en:"cocktail",tr:"كوكتيل",rom:"koktiil",phon:"kah·koo·teh·ru"},{en:"coffee",tr:"قهوة",rom:"qahwa",phon:"koh·hee"},{en:"tea",tr:"شاي",rom:"shaay",phon:"oh·chah"},{en:"juice",tr:"عصير",rom:"asiir",phon:"joo·su"},{en:"whiskey",tr:"ويسكي",rom:"wiiski",phon:"oo·ee·su·kee"},{en:"water",tr:"ماء",rom:"maa",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"معكرونة",rom:"ma'karoona",phon:"pah·su·tah"},{en:"pizza",tr:"بيتزا",rom:"biitza",phon:"pee·zah"},{en:"salad",tr:"سلطة",rom:"salata",phon:"sah·rah·dah"},{en:"steak",tr:"ستيك",rom:"steik",phon:"su·teh·kee"},{en:"sushi",tr:"سوشي",rom:"suushi",phon:"soo·shee"},{en:"burger",tr:"برغر",rom:"burghar",phon:"hahn·bah·gah"},{en:"soup",tr:"شوربة",rom:"shuurba",phon:"soo·pu"},{en:"rice",tr:"أرز",rom:"aruz",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"تيراميسو",rom:"tiraamisu",phon:"tee·rah·mee·su"},{en:"gelato",tr:"جيلاتو",rom:"jilaato",phon:"jeh·rah·toh"},{en:"cheesecake",tr:"تشيزكيك",rom:"tshiizkeik",phon:"chee·zu·keh·kee"},{en:"chocolate",tr:"شوكولاتة",rom:"shookoolaata",phon:"choh·koh·reh·toh"},{en:"cake",tr:"كعكة",rom:"kaka",phon:"keh·kee"},{en:"cookies",tr:"بسكويت",rom:"biskuwiit",phon:"koo·kee"}],ADJ_TASTE:[{en:"refreshing",tr:"منعش",rom:"mun'ish",phon:"sahp·pah·ree"},{en:"rich",tr:"غني",rom:"ghani",phon:"noh·koh"},{en:"light",tr:"خفيف",rom:"khafiif",phon:"kah·roo·ee"},{en:"bitter",tr:"مر",rom:"murr",phon:"nee·gah·ee"},{en:"sweet",tr:"حلو",rom:"hulw",phon:"ah·mah·ee"},{en:"spicy",tr:"حار",rom:"haar",phon:"kah·rah·ee"},{en:"delicious",tr:"لذيذ",rom:"ladhiidh",phon:"oh·ee·shee"}],GREETING:[{en:"Hi",tr:"مرحبا",rom:"marhaba",phon:"yah"},{en:"Hello",tr:"السلام عليكم",rom:"as-salaamu alaykum",phon:"kohn·nee·chee·wah"},{en:"Hey there",tr:"أهلا",rom:"ahlan",phon:"doh·moh"},{en:"Good evening",tr:"مساء الخير",rom:"masaa al-khayr",phon:"kohn·bahn·wah"},{en:"Welcome",tr:"أهلا وسهلا",rom:"ahlan wa sahlan",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"جميلة",rom:"jamiila",phon:"kee·reh·ee"},{en:"lovely",tr:"لطيفة",rom:"latiifa",phon:"su·teh·kee"},{en:"stunning",tr:"مذهلة",rom:"mudh'hila",phon:"mee·toh·reh·ru"},{en:"charming",tr:"ساحرة",rom:"saahira",phon:"mee·ryoh·ku·teh·kee"},{en:"elegant",tr:"أنيقة",rom:"aniiqa",phon:"joh·heen"},{en:"radiant",tr:"مشرقة",rom:"mushriqa",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"مطعم",rom:"mat'am",phon:"reh·su·toh·rahn"},{en:"cafe",tr:"مقهى",rom:"maqha",phon:"kah·feh"},{en:"bar",tr:"بار",rom:"baar",phon:"bah"},{en:"hotel",tr:"فندق",rom:"funduq",phon:"hoh·teh·ru"},{en:"market",tr:"سوق",rom:"suuq",phon:"ee·chee·bah"},{en:"station",tr:"محطة",rom:"mahatta",phon:"eh·kee"}]},
  hi:{DRINKS:[{en:"beer",tr:"बियर",rom:"biyar",phon:"bee·ru"},{en:"wine",tr:"शराब",rom:"sharaab",phon:"wah·een"},{en:"cocktail",tr:"कॉकटेल",rom:"cocktail",phon:"kah·koo·teh·ru"},{en:"coffee",tr:"कॉफी",rom:"coffee",phon:"koh·hee"},{en:"tea",tr:"चाय",rom:"chaay",phon:"oh·chah"},{en:"juice",tr:"जूस",rom:"juus",phon:"joo·su"},{en:"whiskey",tr:"व्हिस्की",rom:"whiskey",phon:"oo·ee·su·kee"},{en:"water",tr:"पानी",rom:"paani",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"पास्ता",rom:"paastaa",phon:"pah·su·tah"},{en:"pizza",tr:"पीज़ा",rom:"piizaa",phon:"pee·zah"},{en:"salad",tr:"सलाद",rom:"salaad",phon:"sah·rah·dah"},{en:"steak",tr:"स्टीक",rom:"steek",phon:"su·teh·kee"},{en:"sushi",tr:"सूशी",rom:"suushi",phon:"soo·shee"},{en:"burger",tr:"बर्गर",rom:"bargar",phon:"hahn·bah·gah"},{en:"soup",tr:"सूप",rom:"suup",phon:"soo·pu"},{en:"rice",tr:"चावल",rom:"chaawal",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"टिरामिसु",rom:"tiraamisu",phon:"tee·rah·mee·su"},{en:"gelato",tr:"जेलाटो",rom:"jelaato",phon:"jeh·rah·toh"},{en:"cheesecake",tr:"चीज़केक",rom:"chiizkeik",phon:"chee·zu·keh·kee"},{en:"chocolate",tr:"चॉकलेट",rom:"choklet",phon:"choh·koh·reh·toh"},{en:"cake",tr:"केक",rom:"kek",phon:"keh·kee"},{en:"cookies",tr:"कुकीज़",rom:"kukiiz",phon:"koo·kee"}],ADJ_TASTE:[{en:"refreshing",tr:"ताज़गी",rom:"taazgi",phon:"sahp·pah·ree"},{en:"rich",tr:"स्वादिष्ट",rom:"swaadisht",phon:"noh·koh"},{en:"light",tr:"हल्का",rom:"halka",phon:"kah·roo·ee"},{en:"bitter",tr:"कड़वा",rom:"kadwa",phon:"nee·gah·ee"},{en:"sweet",tr:"मीठा",rom:"meetha",phon:"ah·mah·ee"},{en:"spicy",tr:"तीखा",rom:"teekha",phon:"kah·rah·ee"},{en:"delicious",tr:"लाजवाब",rom:"laajwaab",phon:"oh·ee·shee"}],GREETING:[{en:"Hi",tr:"नमस्ते",rom:"namaste",phon:"yah"},{en:"Hello",tr:"नमस्कार",rom:"namaskaar",phon:"kohn·nee·chee·wah"},{en:"Hey there",tr:"अरे",rom:"are",phon:"doh·moh"},{en:"Good evening",tr:"शुभ संध्या",rom:"shubh sandhya",phon:"kohn·bahn·wah"},{en:"Welcome",tr:"स्वागत है",rom:"swaagat hai",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"खूबसूरत",rom:"khoobsurat",phon:"kee·reh·ee"},{en:"lovely",tr:"प्यारी",rom:"pyaari",phon:"su·teh·kee"},{en:"stunning",tr:"कमाल",rom:"kamaal",phon:"mee·toh·reh·ru"},{en:"charming",tr:"आकर्षक",rom:"aakarshak",phon:"mee·ryoh·ku·teh·kee"},{en:"elegant",tr:"शानदार",rom:"shaandaar",phon:"joh·heen"},{en:"radiant",tr:"दमकती",rom:"damakti",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"रेस्तरां",rom:"restaraan",phon:"reh·su·toh·rahn"},{en:"cafe",tr:"कैफे",rom:"kaife",phon:"kah·feh"},{en:"bar",tr:"बार",rom:"baar",phon:"bah"},{en:"hotel",tr:"होटल",rom:"hotel",phon:"hoh·teh·ru"},{en:"market",tr:"बाज़ार",rom:"baazaar",phon:"ee·chee·bah"},{en:"station",tr:"स्टेशन",rom:"steshan",phon:"eh·kee"}]},
  pt:{DRINKS:[{en:"beer",tr:"cerveja"},{en:"wine",tr:"vinho"},{en:"cocktail",tr:"coquetel"},{en:"coffee",tr:"café"},{en:"tea",tr:"chá"},{en:"juice",tr:"suco"},{en:"whiskey",tr:"uísque"},{en:"water",tr:"água"}],FOOD:[{en:"pasta",tr:"massa"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"salada"},{en:"steak",tr:"bife"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"hambúrguer"},{en:"soup",tr:"sopa"},{en:"rice",tr:"arroz"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"sorvete"},{en:"cheesecake",tr:"cheesecake"},{en:"chocolate",tr:"chocolate"},{en:"cake",tr:"bolo"},{en:"cookies",tr:"biscoitos"}],ADJ_TASTE:[{en:"refreshing",tr:"refrescante"},{en:"rich",tr:"rico"},{en:"light",tr:"leve"},{en:"bitter",tr:"amargo"},{en:"sweet",tr:"doce"},{en:"spicy",tr:"picante"},{en:"delicious",tr:"delicioso"}],GREETING:[{en:"Hi",tr:"Oi"},{en:"Hello",tr:"Olá"},{en:"Hey there",tr:"E aí"},{en:"Good evening",tr:"Boa noite"},{en:"Welcome",tr:"Bem-vindo"}],COMPLIMENT:[{en:"beautiful",tr:"bonita"},{en:"lovely",tr:"adorável"},{en:"stunning",tr:"deslumbrante"},{en:"charming",tr:"encantador"},{en:"elegant",tr:"elegante"},{en:"radiant",tr:"radiante"}],PLACE:[{en:"restaurant",tr:"restaurante"},{en:"cafe",tr:"café"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hotel"},{en:"market",tr:"mercado"},{en:"station",tr:"estação"}]},
  de:{DRINKS:[{en:"beer",tr:"Bier"},{en:"wine",tr:"Wein"},{en:"cocktail",tr:"Cocktail"},{en:"coffee",tr:"Kaffee"},{en:"tea",tr:"Tee"},{en:"juice",tr:"Saft"},{en:"whiskey",tr:"Whisky"},{en:"water",tr:"Wasser"}],FOOD:[{en:"pasta",tr:"Pasta"},{en:"pizza",tr:"Pizza"},{en:"salad",tr:"Salat"},{en:"steak",tr:"Steak"},{en:"sushi",tr:"Sushi"},{en:"burger",tr:"Burger"},{en:"soup",tr:"Suppe"},{en:"rice",tr:"Reis"}],DESSERT:[{en:"tiramisu",tr:"Tiramisu"},{en:"gelato",tr:"Eis"},{en:"cheesecake",tr:"Käsekuchen"},{en:"chocolate",tr:"Schokolade"},{en:"cake",tr:"Kuchen"},{en:"cookies",tr:"Kekse"}],ADJ_TASTE:[{en:"refreshing",tr:"erfrischend"},{en:"rich",tr:"reichhaltig"},{en:"light",tr:"leicht"},{en:"bitter",tr:"bitter"},{en:"sweet",tr:"süß"},{en:"spicy",tr:"scharf"},{en:"delicious",tr:"köstlich"}],GREETING:[{en:"Hi",tr:"Hallo"},{en:"Hello",tr:"Guten Tag"},{en:"Hey there",tr:"Na"},{en:"Good evening",tr:"Guten Abend"},{en:"Welcome",tr:"Willkommen"}],COMPLIMENT:[{en:"beautiful",tr:"wunderschön"},{en:"lovely",tr:"reizend"},{en:"stunning",tr:"atemberaubend"},{en:"charming",tr:"charmant"},{en:"elegant",tr:"elegant"},{en:"radiant",tr:"strahlend"}],PLACE:[{en:"restaurant",tr:"Restaurant"},{en:"cafe",tr:"Café"},{en:"bar",tr:"Bar"},{en:"hotel",tr:"Hotel"},{en:"market",tr:"Markt"},{en:"station",tr:"Bahnhof"}]},
  ru:{DRINKS:[{en:"beer",tr:"пиво",rom:"pivo",phon:"bee·ru"},{en:"wine",tr:"вино",rom:"vino",phon:"wah·een"},{en:"cocktail",tr:"коктейль",rom:"kokteyl'",phon:"kah·koo·teh·ru"},{en:"coffee",tr:"кофе",rom:"kofe",phon:"koh·hee"},{en:"tea",tr:"чай",rom:"chay",phon:"oh·chah"},{en:"juice",tr:"сок",rom:"sok",phon:"joo·su"},{en:"whiskey",tr:"виски",rom:"viski",phon:"oo·ee·su·kee"},{en:"water",tr:"вода",rom:"voda",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"паста",rom:"pasta",phon:"pah·su·tah"},{en:"pizza",tr:"пицца",rom:"pitstsa",phon:"pee·zah"},{en:"salad",tr:"салат",rom:"salat",phon:"sah·rah·dah"},{en:"steak",tr:"стейк",rom:"steyk",phon:"su·teh·kee"},{en:"sushi",tr:"суши",rom:"sushi",phon:"soo·shee"},{en:"burger",tr:"бургер",rom:"burger",phon:"hahn·bah·gah"},{en:"soup",tr:"суп",rom:"sup",phon:"soo·pu"},{en:"rice",tr:"рис",rom:"ris",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"тирамису",rom:"tiramisu",phon:"tee·rah·mee·su"},{en:"gelato",tr:"джелато",rom:"dzhelato",phon:"jeh·rah·toh"},{en:"cheesecake",tr:"чизкейк",rom:"chiizkeyk",phon:"chee·zu·keh·kee"},{en:"chocolate",tr:"шоколад",rom:"shokolad",phon:"choh·koh·reh·toh"},{en:"cake",tr:"торт",rom:"tort",phon:"keh·kee"},{en:"cookies",tr:"печенье",rom:"pechen'ye",phon:"koo·kee"}],ADJ_TASTE:[{en:"refreshing",tr:"освежающий",rom:"osvezhayushchiy",phon:"sahp·pah·ree"},{en:"rich",tr:"насыщенный",rom:"nasyshchennyy",phon:"noh·koh"},{en:"light",tr:"лёгкий",rom:"lyogkiy",phon:"kah·roo·ee"},{en:"bitter",tr:"горький",rom:"gor'kiy",phon:"nee·gah·ee"},{en:"sweet",tr:"сладкий",rom:"sladkiy",phon:"ah·mah·ee"},{en:"spicy",tr:"острый",rom:"ostryy",phon:"kah·rah·ee"},{en:"delicious",tr:"вкусный",rom:"vkusnyy",phon:"oh·ee·shee"}],GREETING:[{en:"Hi",tr:"Привет",rom:"privet",phon:"yah"},{en:"Hello",tr:"Здравствуйте",rom:"zdravstvuyte",phon:"kohn·nee·chee·wah"},{en:"Hey there",tr:"Эй",rom:"ey",phon:"doh·moh"},{en:"Good evening",tr:"Добрый вечер",rom:"dobryy vecher",phon:"kohn·bahn·wah"},{en:"Welcome",tr:"Добро пожаловать",rom:"dobro pozhalovat'",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"красивая",rom:"krasivaya",phon:"kee·reh·ee"},{en:"lovely",tr:"милая",rom:"milaya",phon:"su·teh·kee"},{en:"stunning",tr:"потрясающая",rom:"potryasayushchaya",phon:"mee·toh·reh·ru"},{en:"charming",tr:"очаровательная",rom:"ocharovatel'naya",phon:"mee·ryoh·ku·teh·kee"},{en:"elegant",tr:"элегантная",rom:"elegantnaya",phon:"joh·heen"},{en:"radiant",tr:"сияющая",rom:"siyayushchaya",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"ресторан",rom:"restoran",phon:"reh·su·toh·rahn"},{en:"cafe",tr:"кафе",rom:"kafe",phon:"kah·feh"},{en:"bar",tr:"бар",rom:"bar",phon:"bah"},{en:"hotel",tr:"отель",rom:"otel'",phon:"hoh·teh·ru"},{en:"market",tr:"рынок",rom:"rynok",phon:"ee·chee·bah"},{en:"station",tr:"вокзал",rom:"vokzal",phon:"eh·kee"}]},
  th:{DRINKS:[{en:"beer",tr:"เบียร์",rom:"bia",phon:"bee·ru"},{en:"wine",tr:"ไวน์",rom:"wai",phon:"wah·een"},{en:"cocktail",tr:"ค็อกเทล",rom:"khokthen",phon:"kah·koo·teh·ru"},{en:"coffee",tr:"กาแฟ",rom:"kaafae",phon:"koh·hee"},{en:"tea",tr:"ชา",rom:"chaa",phon:"oh·chah"},{en:"juice",tr:"น้ำผลไม้",rom:"nam phonlamai",phon:"joo·su"},{en:"whiskey",tr:"วิสกี้",rom:"wisakii",phon:"oo·ee·su·kee"},{en:"water",tr:"น้ำ",rom:"nam",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"พาสต้า",rom:"phaastaa",phon:"pah·su·tah"},{en:"pizza",tr:"พิซซ่า",rom:"phitsaa",phon:"pee·zah"},{en:"salad",tr:"สลัด",rom:"salat",phon:"sah·rah·dah"},{en:"steak",tr:"สเต็ก",rom:"satek",phon:"su·teh·kee"},{en:"sushi",tr:"ซูชิ",rom:"suuchi",phon:"soo·shee"},{en:"burger",tr:"เบอร์เกอร์",rom:"boekoe",phon:"hahn·bah·gah"},{en:"soup",tr:"ซุป",rom:"sup",phon:"soo·pu"},{en:"rice",tr:"ข้าว",rom:"khaao",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"ทิรามิสู",rom:"thiraamisu",phon:"tee·rah·mee·su"},{en:"gelato",tr:"เจลาโต้",rom:"jelaato",phon:"jeh·rah·toh"},{en:"cheesecake",tr:"ชีสเค้ก",rom:"chiiskheek",phon:"chee·zu·keh·kee"},{en:"chocolate",tr:"ช็อกโกแลต",rom:"chokkolat",phon:"choh·koh·reh·toh"},{en:"cake",tr:"เค้ก",rom:"khek",phon:"keh·kee"},{en:"cookies",tr:"คุกกี้",rom:"khukki",phon:"koo·kee"}],ADJ_TASTE:[{en:"refreshing",tr:"สดชื่น",rom:"sot chuen",phon:"sahp·pah·ree"},{en:"rich",tr:"เข้มข้น",rom:"khem khon",phon:"noh·koh"},{en:"light",tr:"เบา",rom:"bao",phon:"kah·roo·ee"},{en:"bitter",tr:"ขม",rom:"khom",phon:"nee·gah·ee"},{en:"sweet",tr:"หวาน",rom:"waan",phon:"ah·mah·ee"},{en:"spicy",tr:"เผ็ด",rom:"phet",phon:"kah·rah·ee"},{en:"delicious",tr:"อร่อย",rom:"aroi",phon:"oh·ee·shee"}],GREETING:[{en:"Hi",tr:"สวัสดี",rom:"sawatdii",phon:"yah"},{en:"Hello",tr:"สวัสดีครับ",rom:"sawatdii khrap",phon:"kohn·nee·chee·wah"},{en:"Hey there",tr:"หวัดดี",rom:"watdii",phon:"doh·moh"},{en:"Good evening",tr:"สวัสดีตอนเย็น",rom:"sawatdii ton yen",phon:"kohn·bahn·wah"},{en:"Welcome",tr:"ยินดีต้อนรับ",rom:"yindii tonrap",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"สวย",rom:"suay",phon:"kee·reh·ee"},{en:"lovely",tr:"น่ารัก",rom:"naa rak",phon:"su·teh·kee"},{en:"stunning",tr:"งดงาม",rom:"ngot ngaam",phon:"mee·toh·reh·ru"},{en:"charming",tr:"มีเสน่ห์",rom:"mii sanee",phon:"mee·ryoh·ku·teh·kee"},{en:"elegant",tr:"สง่างาม",rom:"sangaa ngaam",phon:"joh·heen"},{en:"radiant",tr:"เปล่งปลั่ง",rom:"pleng plang",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"ร้านอาหาร",rom:"raan aahaan",phon:"reh·su·toh·rahn"},{en:"cafe",tr:"คาเฟ่",rom:"kaafee",phon:"kah·feh"},{en:"bar",tr:"บาร์",rom:"baa",phon:"bah"},{en:"hotel",tr:"โรงแรม",rom:"roong raem",phon:"hoh·teh·ru"},{en:"market",tr:"ตลาด",rom:"talaat",phon:"ee·chee·bah"},{en:"station",tr:"สถานี",rom:"sathaanii",phon:"eh·kee"}]},
  tr:{DRINKS:[{en:"beer",tr:"bira"},{en:"wine",tr:"şarap"},{en:"cocktail",tr:"kokteyl"},{en:"coffee",tr:"kahve"},{en:"tea",tr:"çay"},{en:"juice",tr:"meyve suyu"},{en:"whiskey",tr:"viski"},{en:"water",tr:"su"}],FOOD:[{en:"pasta",tr:"makarna"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"salata"},{en:"steak",tr:"biftek"},{en:"sushi",tr:"suşi"},{en:"burger",tr:"hamburger"},{en:"soup",tr:"çorba"},{en:"rice",tr:"pilav"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"dondurma"},{en:"cheesecake",tr:"cheesecake"},{en:"chocolate",tr:"çikolata"},{en:"cake",tr:"pasta"},{en:"cookies",tr:"kurabiye"}],ADJ_TASTE:[{en:"refreshing",tr:"ferahlatıcı"},{en:"rich",tr:"zengin"},{en:"light",tr:"hafif"},{en:"bitter",tr:"acı"},{en:"sweet",tr:"tatlı"},{en:"spicy",tr:"baharatlı"},{en:"delicious",tr:"lezzetli"}],GREETING:[{en:"Hi",tr:"Merhaba"},{en:"Hello",tr:"Selam"},{en:"Hey there",tr:"Hey"},{en:"Good evening",tr:"İyi akşamlar"},{en:"Welcome",tr:"Hoş geldiniz"}],COMPLIMENT:[{en:"beautiful",tr:"güzel"},{en:"lovely",tr:"sevimli"},{en:"stunning",tr:"muhteşem"},{en:"charming",tr:"çekici"},{en:"elegant",tr:"zarif"},{en:"radiant",tr:"ışıl ışıl"}],PLACE:[{en:"restaurant",tr:"restoran"},{en:"cafe",tr:"kafe"},{en:"bar",tr:"bar"},{en:"hotel",tr:"otel"},{en:"market",tr:"pazar"},{en:"station",tr:"istasyon"}]},
  vi:{DRINKS:[{en:"beer",tr:"bia"},{en:"wine",tr:"rượu vang"},{en:"cocktail",tr:"cocktail"},{en:"coffee",tr:"cà phê"},{en:"tea",tr:"trà"},{en:"juice",tr:"nước ép"},{en:"whiskey",tr:"rượu whisky"},{en:"water",tr:"nước"}],FOOD:[{en:"pasta",tr:"mì Ý"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"salad"},{en:"steak",tr:"bít tết"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"bánh mì kẹp"},{en:"soup",tr:"canh"},{en:"rice",tr:"cơm"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"kem"},{en:"cheesecake",tr:"bánh phô mai"},{en:"chocolate",tr:"sô cô la"},{en:"cake",tr:"bánh ngọt"},{en:"cookies",tr:"bánh quy"}],ADJ_TASTE:[{en:"refreshing",tr:"mát mẻ"},{en:"rich",tr:"đậm đà"},{en:"light",tr:"nhẹ"},{en:"bitter",tr:"đắng"},{en:"sweet",tr:"ngọt"},{en:"spicy",tr:"cay"},{en:"delicious",tr:"ngon"}],GREETING:[{en:"Hi",tr:"Xin chào"},{en:"Hello",tr:"Chào bạn"},{en:"Hey there",tr:"Ê"},{en:"Good evening",tr:"Chào buổi tối"},{en:"Welcome",tr:"Chào mừng"}],COMPLIMENT:[{en:"beautiful",tr:"đẹp"},{en:"lovely",tr:"dễ thương"},{en:"stunning",tr:"tuyệt đẹp"},{en:"charming",tr:"quyến rũ"},{en:"elegant",tr:"thanh lịch"},{en:"radiant",tr:"rạng rỡ"}],PLACE:[{en:"restaurant",tr:"nhà hàng"},{en:"cafe",tr:"quán cà phê"},{en:"bar",tr:"quán bar"},{en:"hotel",tr:"khách sạn"},{en:"market",tr:"chợ"},{en:"station",tr:"ga"}]},
  tl:{DRINKS:[{en:"beer",tr:"beer"},{en:"wine",tr:"alak"},{en:"cocktail",tr:"cocktail"},{en:"coffee",tr:"kape"},{en:"tea",tr:"tsaa"},{en:"juice",tr:"juice"},{en:"whiskey",tr:"whiskey"},{en:"water",tr:"tubig"}],FOOD:[{en:"pasta",tr:"pasta"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"salad"},{en:"steak",tr:"steak"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"burger"},{en:"soup",tr:"sopas"},{en:"rice",tr:"kanin"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"sorbetes"},{en:"cheesecake",tr:"cheesecake"},{en:"chocolate",tr:"tsokolate"},{en:"cake",tr:"keyk"},{en:"cookies",tr:"cookies"}],ADJ_TASTE:[{en:"refreshing",tr:"nakakapreskong"},{en:"rich",tr:"masarap"},{en:"light",tr:"magaan"},{en:"bitter",tr:"mapait"},{en:"sweet",tr:"matamis"},{en:"spicy",tr:"maanghang"},{en:"delicious",tr:"napakasarap"}],GREETING:[{en:"Hi",tr:"Kumusta"},{en:"Hello",tr:"Magandang araw"},{en:"Hey there",tr:"Uy"},{en:"Good evening",tr:"Magandang gabi"},{en:"Welcome",tr:"Maligayang pagdating"}],COMPLIMENT:[{en:"beautiful",tr:"maganda"},{en:"lovely",tr:"kaibig-ibig"},{en:"stunning",tr:"napakaganda"},{en:"charming",tr:"kaakit-akit"},{en:"elegant",tr:"elegante"},{en:"radiant",tr:"maningning"}],PLACE:[{en:"restaurant",tr:"restawran"},{en:"cafe",tr:"kapihan"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hotel"},{en:"market",tr:"palengke"},{en:"station",tr:"istasyon"}]},
  nl:{DRINKS:[{en:"beer",tr:"bier"},{en:"wine",tr:"wijn"},{en:"cocktail",tr:"cocktail"},{en:"coffee",tr:"koffie"},{en:"tea",tr:"thee"},{en:"juice",tr:"sap"},{en:"whiskey",tr:"whisky"},{en:"water",tr:"water"}],FOOD:[{en:"pasta",tr:"pasta"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"salade"},{en:"steak",tr:"biefstuk"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"hamburger"},{en:"soup",tr:"soep"},{en:"rice",tr:"rijst"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"ijs"},{en:"cheesecake",tr:"kwarktaart"},{en:"chocolate",tr:"chocolade"},{en:"cake",tr:"taart"},{en:"cookies",tr:"koekjes"}],ADJ_TASTE:[{en:"refreshing",tr:"verfrissend"},{en:"rich",tr:"rijk"},{en:"light",tr:"licht"},{en:"bitter",tr:"bitter"},{en:"sweet",tr:"zoet"},{en:"spicy",tr:"pittig"},{en:"delicious",tr:"heerlijk"}],GREETING:[{en:"Hi",tr:"Hoi"},{en:"Hello",tr:"Hallo"},{en:"Hey there",tr:"Hé"},{en:"Good evening",tr:"Goedenavond"},{en:"Welcome",tr:"Welkom"}],COMPLIMENT:[{en:"beautiful",tr:"mooi"},{en:"lovely",tr:"lief"},{en:"stunning",tr:"prachtig"},{en:"charming",tr:"charmant"},{en:"elegant",tr:"elegant"},{en:"radiant",tr:"stralend"}],PLACE:[{en:"restaurant",tr:"restaurant"},{en:"cafe",tr:"café"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hotel"},{en:"market",tr:"markt"},{en:"station",tr:"station"}]},
  sv:{DRINKS:[{en:"beer",tr:"öl"},{en:"wine",tr:"vin"},{en:"cocktail",tr:"cocktail"},{en:"coffee",tr:"kaffe"},{en:"tea",tr:"te"},{en:"juice",tr:"juice"},{en:"whiskey",tr:"whisky"},{en:"water",tr:"vatten"}],FOOD:[{en:"pasta",tr:"pasta"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"sallad"},{en:"steak",tr:"biff"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"hamburgare"},{en:"soup",tr:"soppa"},{en:"rice",tr:"ris"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"glass"},{en:"cheesecake",tr:"cheesecake"},{en:"chocolate",tr:"choklad"},{en:"cake",tr:"tårta"},{en:"cookies",tr:"kakor"}],ADJ_TASTE:[{en:"refreshing",tr:"uppfriskande"},{en:"rich",tr:"rik"},{en:"light",tr:"lätt"},{en:"bitter",tr:"bitter"},{en:"sweet",tr:"söt"},{en:"spicy",tr:"kryddig"},{en:"delicious",tr:"utsökt"}],GREETING:[{en:"Hi",tr:"Hej"},{en:"Hello",tr:"God dag"},{en:"Hey there",tr:"Tjena"},{en:"Good evening",tr:"God kväll"},{en:"Welcome",tr:"Välkommen"}],COMPLIMENT:[{en:"beautiful",tr:"vacker"},{en:"lovely",tr:"söt"},{en:"stunning",tr:"fantastisk"},{en:"charming",tr:"charmig"},{en:"elegant",tr:"elegant"},{en:"radiant",tr:"strålande"}],PLACE:[{en:"restaurant",tr:"restaurang"},{en:"cafe",tr:"kafé"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hotell"},{en:"market",tr:"marknad"},{en:"station",tr:"station"}]},
  pl:{DRINKS:[{en:"beer",tr:"piwo"},{en:"wine",tr:"wino"},{en:"cocktail",tr:"koktajl"},{en:"coffee",tr:"kawa"},{en:"tea",tr:"herbata"},{en:"juice",tr:"sok"},{en:"whiskey",tr:"whisky"},{en:"water",tr:"woda"}],FOOD:[{en:"pasta",tr:"makaron"},{en:"pizza",tr:"pizza"},{en:"salad",tr:"sałatka"},{en:"steak",tr:"stek"},{en:"sushi",tr:"sushi"},{en:"burger",tr:"burger"},{en:"soup",tr:"zupa"},{en:"rice",tr:"ryż"}],DESSERT:[{en:"tiramisu",tr:"tiramisu"},{en:"gelato",tr:"lody"},{en:"cheesecake",tr:"sernik"},{en:"chocolate",tr:"czekolada"},{en:"cake",tr:"ciasto"},{en:"cookies",tr:"ciasteczka"}],ADJ_TASTE:[{en:"refreshing",tr:"orzeźwiający"},{en:"rich",tr:"bogaty"},{en:"light",tr:"lekki"},{en:"bitter",tr:"gorzki"},{en:"sweet",tr:"słodki"},{en:"spicy",tr:"ostry"},{en:"delicious",tr:"pyszny"}],GREETING:[{en:"Hi",tr:"Cześć"},{en:"Hello",tr:"Dzień dobry"},{en:"Hey there",tr:"Hej"},{en:"Good evening",tr:"Dobry wieczór"},{en:"Welcome",tr:"Witaj"}],COMPLIMENT:[{en:"beautiful",tr:"piękna"},{en:"lovely",tr:"urocza"},{en:"stunning",tr:"oszałamiająca"},{en:"charming",tr:"czarujący"},{en:"elegant",tr:"elegancka"},{en:"radiant",tr:"promieniejąca"}],PLACE:[{en:"restaurant",tr:"restauracja"},{en:"cafe",tr:"kawiarnia"},{en:"bar",tr:"bar"},{en:"hotel",tr:"hotel"},{en:"market",tr:"targ"},{en:"station",tr:"dworzec"}]},
  bg:{DRINKS:[{en:"coffee",tr:"кафе",rom:"kafe",phon:"koh·hee"},{en:"wine",tr:"вино",rom:"vino",phon:"wah·een"},{en:"beer",tr:"бира",rom:"bira",phon:"bee·ru"},{en:"cocktail",tr:"коктейл",rom:"kokteyl",phon:"kah·koo·teh·ru"},{en:"tea",tr:"чай",rom:"chay",phon:"oh·chah"},{en:"juice",tr:"сок",rom:"sok",phon:"joo·su"},{en:"whiskey",tr:"уиски",rom:"uiski",phon:"oo·ee·su·kee"},{en:"water",tr:"вода",rom:"voda",phon:"mee·zu"}],FOOD:[{en:"pasta",tr:"паста",rom:"pasta",phon:"pah·su·tah"},{en:"steak",tr:"стек",rom:"stek",phon:"su·teh·kee"},{en:"sushi",tr:"суши",rom:"sushi",phon:"soo·shee"},{en:"burger",tr:"бургер",rom:"burger",phon:"hahn·bah·gah"},{en:"soup",tr:"супа",rom:"supa",phon:"soo·pu"},{en:"rice",tr:"ориз",rom:"oriz",phon:"goh·hahn"}],DESSERT:[{en:"tiramisu",tr:"тирамису",rom:"tiramisu",phon:"tee·rah·mee·su"},{en:"ice cream",tr:"сладолед",rom:"sladoled"},{en:"chocolate",tr:"шоколад",rom:"shokolad",phon:"choh·koh·reh·toh"},{en:"cake",tr:"торта",rom:"torta",phon:"keh·kee"},{en:"cookies",tr:"бисквити",rom:"biskviti",phon:"koo·kee"}],ADJ_TASTE:[{en:"delicious",tr:"вкусен",rom:"vkusen",phon:"oh·ee·shee"},{en:"sweet",tr:"сладък",rom:"sladak",phon:"ah·mah·ee"},{en:"rich",tr:"богат",rom:"bogat",phon:"noh·koh"},{en:"spicy",tr:"лют",rom:"lyut",phon:"kah·rah·ee"},{en:"amazing",tr:"невероятен",rom:"neveroiaten"}],GREETING:[{en:"Hello",tr:"Здравей",rom:"Zdravey",phon:"kohn·nee·chee·wah"},{en:"Good evening",tr:"Добър вечер",rom:"Dobar vecher",phon:"kohn·bahn·wah"},{en:"Hey",tr:"Хей",rom:"Hey"},{en:"Welcome",tr:"Добре дошъл",rom:"Dobre doshal",phon:"yoh·koh·soh"}],COMPLIMENT:[{en:"beautiful",tr:"красива",rom:"krasiva",phon:"kee·reh·ee"},{en:"stunning",tr:"зашеметяваща",rom:"zashemet'avashta",phon:"mee·toh·reh·ru"},{en:"elegant",tr:"елегантна",rom:"elegantna",phon:"joh·heen"},{en:"charming",tr:"очарователна",rom:"ocharovatelna",phon:"mee·ryoh·ku·teh·kee"},{en:"radiant",tr:"сияйна",rom:"siyayna",phon:"kah·gah·yah·ku"}],PLACE:[{en:"restaurant",tr:"ресторант",rom:"restorant",phon:"reh·su·toh·rahn"},{en:"hotel",tr:"хотел",rom:"hotel",phon:"hoh·teh·ru"},{en:"station",tr:"гара",rom:"gara",phon:"eh·kee"},{en:"market",tr:"пазар",rom:"pazar",phon:"ee·chee·bah"}]}
};

// ── Phrase template keys ──

export type PhraseKey =
  "flirty_hello"|"warm_hello"|"ask_drinks"|"like_most"|"smile_compliment"|
  "try_food"|"after_dinner"|"polite_help"|"where_place"|"order_drink"|
  "city_is"|"formal_thanks"|"offer_drink"|"continue_over"|"good_to_see"|
  "food_is"|"nice_to_meet"|"prefer_or";

export const PHRASE_KEYS: PhraseKey[] = [
  "flirty_hello","warm_hello","ask_drinks","like_most","smile_compliment",
  "try_food","after_dinner","polite_help","where_place","order_drink",
  "city_is","formal_thanks","offer_drink","continue_over","good_to_see",
  "food_is","nice_to_meet","prefer_or"
];

// TR and TR_ROM are large — kept as typed Record for SDK use
// See lingua-franca.html for full data
// For the glasses we primarily show: greeting + 2–3 phrases per scenario

export const TR: Record<string, Record<PhraseKey, string>> = {
  id:{flirty_hello:"[GREETING], malam ini kamu terlihat sangat [COMPLIMENT].",warm_hello:"[GREETING], senang bertemu denganmu. Kamu terlihat [COMPLIMENT].",ask_drinks:"Jenis [DRINKS] apa yang kamu suka?",like_most:"Saya paling suka [DRINKS], rasanya sangat [ADJ_TASTE].",smile_compliment:"Senyummu sangat [COMPLIMENT].",try_food:"Mau coba [FOOD] di sini? Katanya enak sekali.",after_dinner:"Setelah makan, mau ambil [DESSERT]?",polite_help:"[GREETING], bisakah kamu membantu saya?",where_place:"Di mana [PLACE] terdekat?",order_drink:"Saya mau [DRINKS], tolong.",city_is:"Kota ini benar-benar [ADJ_TASTE].",formal_thanks:"[GREETING], terima kasih atas waktunya hari ini.",offer_drink:"Boleh saya tawarkan [DRINKS]?",continue_over:"Mari kita lanjutkan sambil [FOOD].",good_to_see:"[GREETING]! Senang sekali bertemu.",food_is:"[FOOD] ini sangat [ADJ_TASTE].",nice_to_meet:"[GREETING], senang bertemu denganmu.",prefer_or:"Kamu lebih suka [DRINKS] atau [DRINKS]?"},
  es:{flirty_hello:"[GREETING], esta noche te ves realmente [COMPLIMENT].",warm_hello:"[GREETING], qué gusto verte. Te ves [COMPLIMENT].",ask_drinks:"¿Qué tipo de [DRINKS] te gusta?",like_most:"Me gusta más el [DRINKS], es muy [ADJ_TASTE].",smile_compliment:"Tu sonrisa es muy [COMPLIMENT].",try_food:"¿Probamos la [FOOD] aquí?",after_dinner:"Después de cenar, ¿un [DESSERT]?",polite_help:"[GREETING], ¿podrías ayudarme?",where_place:"¿Dónde está el [PLACE] más cercano?",order_drink:"Me gustaría un [DRINKS], por favor.",city_is:"Esta ciudad es muy [ADJ_TASTE].",formal_thanks:"[GREETING], gracias por su tiempo hoy.",offer_drink:"¿Me permite ofrecerle un [DRINKS]?",continue_over:"¿Continuamos con una [FOOD]?",good_to_see:"¡[GREETING]! Qué gusto verte.",food_is:"Esta [FOOD] está muy [ADJ_TASTE].",nice_to_meet:"[GREETING], mucho gusto.",prefer_or:"¿Prefieres [DRINKS] o [DRINKS]?"},
  fr:{flirty_hello:"[GREETING], tu es vraiment [COMPLIMENT] ce soir.",warm_hello:"[GREETING], ravi de te voir. Tu es [COMPLIMENT].",ask_drinks:"Quel type de [DRINKS] aimes-tu ?",like_most:"J'aime le [DRINKS] — c'est très [ADJ_TASTE].",smile_compliment:"Ton sourire est vraiment [COMPLIMENT].",try_food:"On essaie les [FOOD] ici ?",after_dinner:"Après le dîner, un [DESSERT] ?",polite_help:"[GREETING], pouvez-vous m'aider ?",where_place:"Où est le [PLACE] le plus proche ?",order_drink:"Je voudrais un [DRINKS], s'il vous plaît.",city_is:"Cette ville est vraiment [ADJ_TASTE].",formal_thanks:"[GREETING], merci pour votre temps.",offer_drink:"Puis-je vous offrir un [DRINKS] ?",continue_over:"On continue autour d'un [FOOD] ?",good_to_see:"[GREETING] ! Ravi de te voir.",food_is:"Ce [FOOD] est très [ADJ_TASTE].",nice_to_meet:"[GREETING], enchanté.",prefer_or:"Tu préfères le [DRINKS] ou le [DRINKS] ?"},
  ja:{flirty_hello:"[GREETING]、今夜はとても[COMPLIMENT]ですね。",warm_hello:"[GREETING]、会えて嬉しいです。とても[COMPLIMENT]。",ask_drinks:"どんな[DRINKS]が好きですか？",like_most:"[DRINKS]が一番好きです。とても[ADJ_TASTE]。",smile_compliment:"あなたの笑顔、本当に[COMPLIMENT]。",try_food:"ここの[FOOD]、食べてみませんか？",after_dinner:"食事のあと、[DESSERT]どう？",polite_help:"[GREETING]、手伝っていただけますか？",where_place:"一番近い[PLACE]はどこですか？",order_drink:"[DRINKS]をください。",city_is:"この街、とても[ADJ_TASTE]。",formal_thanks:"[GREETING]、本日はお時間をありがとうございます。",offer_drink:"[DRINKS]はいかがですか？",continue_over:"[FOOD]を食べながら続けましょうか？",good_to_see:"[GREETING]！ 会えて嬉しい。",food_is:"この[FOOD]、とても[ADJ_TASTE]。",nice_to_meet:"[GREETING]、初めまして。",prefer_or:"[DRINKS]と[DRINKS]、どっちが好き？"},
  it:{flirty_hello:"[GREETING], stasera sei davvero [COMPLIMENT].",warm_hello:"[GREETING], che piacere vederti. Sei [COMPLIMENT].",ask_drinks:"Che tipo di [DRINKS] ti piace?",like_most:"Mi piace di più la [DRINKS], è molto [ADJ_TASTE].",smile_compliment:"Il tuo sorriso è davvero [COMPLIMENT].",try_food:"Proviamo la [FOOD] qui?",after_dinner:"Dopo cena, un [DESSERT]?",polite_help:"[GREETING], può aiutarmi?",where_place:"Dov'è il [PLACE] più vicino?",order_drink:"Vorrei un [DRINKS], per favore.",city_is:"Questa città è molto [ADJ_TASTE].",formal_thanks:"[GREETING], grazie per il suo tempo oggi.",offer_drink:"Posso offrirle un [DRINKS]?",continue_over:"Continuiamo davanti a una [FOOD]?",good_to_see:"[GREETING]! Che piacere vederti.",food_is:"Questa [FOOD] è molto [ADJ_TASTE].",nice_to_meet:"[GREETING], piacere di conoscerti.",prefer_or:"Preferisci il [DRINKS] o il [DRINKS]?"},
  zh:{flirty_hello:"[GREETING]，你今晚真的很[COMPLIMENT]。",warm_hello:"[GREETING]，见到你真高兴。你很[COMPLIMENT]。",ask_drinks:"你喜欢什么样的[DRINKS]？",like_most:"我最喜欢[DRINKS]，非常[ADJ_TASTE]。",smile_compliment:"你的笑容真的很[COMPLIMENT]。",try_food:"我们试试这里的[FOOD]吧？",after_dinner:"吃完饭后，要不要来个[DESSERT]？",polite_help:"[GREETING]，你能帮帮我吗？",where_place:"最近的[PLACE]在哪里？",order_drink:"我要一杯[DRINKS]，谢谢。",city_is:"这个城市真的很[ADJ_TASTE]。",formal_thanks:"[GREETING]，感谢您今天的时间。",offer_drink:"我可以请你喝[DRINKS]吗？",continue_over:"我们边吃[FOOD]边继续吧？",good_to_see:"[GREETING]！见到你真高兴。",food_is:"这个[FOOD]非常[ADJ_TASTE]。",nice_to_meet:"[GREETING]，很高兴认识你。",prefer_or:"你更喜欢[DRINKS]还是[DRINKS]？"},
  ko:{flirty_hello:"[GREETING], 오늘 밤 정말 [COMPLIMENT]이에요.",warm_hello:"[GREETING], 만나서 반가워요. [COMPLIMENT]이에요.",ask_drinks:"어떤 [DRINKS]를 좋아하세요?",like_most:"[DRINKS]가 제일 좋아요, 정말 [ADJ_TASTE]해요.",smile_compliment:"미소가 정말 [COMPLIMENT]이에요.",try_food:"여기 [FOOD] 먹어볼까요?",after_dinner:"식사 후에 [DESSERT] 어때요?",polite_help:"[GREETING], 좀 도와주실 수 있을까요?",where_place:"가장 가까운 [PLACE]이 어디예요?",order_drink:"[DRINKS] 주세요.",city_is:"이 도시 정말 [ADJ_TASTE]이에요.",formal_thanks:"[GREETING], 오늘 시간 내주셔서 감사합니다.",offer_drink:"[DRINKS] 한 잔 하시겠어요?",continue_over:"[FOOD] 먹으면서 계속할까요?",good_to_see:"[GREETING]! 만나서 반가워요.",food_is:"이 [FOOD] 정말 [ADJ_TASTE]이에요.",nice_to_meet:"[GREETING], 반갑습니다.",prefer_or:"[DRINKS]와 [DRINKS] 중에 뭐가 좋으세요?"},
  ar:{flirty_hello:"[GREETING]، أنتِ فعلاً [COMPLIMENT] الليلة.",warm_hello:"[GREETING]، سعيد بلقائك. أنتِ [COMPLIMENT].",ask_drinks:"أي نوع من [DRINKS] تفضلين؟",like_most:"أفضل [DRINKS]، طعمه [ADJ_TASTE] جداً.",smile_compliment:"ابتسامتك [COMPLIMENT] جداً.",try_food:"هل نجرب [FOOD] هنا؟",after_dinner:"بعد العشاء، [DESSERT]؟",polite_help:"[GREETING]، هل يمكنك مساعدتي؟",where_place:"أين أقرب [PLACE]؟",order_drink:"أريد [DRINKS] من فضلك.",city_is:"هذه المدينة [ADJ_TASTE] جداً.",formal_thanks:"[GREETING]، شكراً على وقتك اليوم.",offer_drink:"هل أقدم لك [DRINKS]؟",continue_over:"هل نكمل مع [FOOD]؟",good_to_see:"[GREETING]! سعيد بلقائك.",food_is:"هذا [FOOD] [ADJ_TASTE] جداً.",nice_to_meet:"[GREETING]، تشرفنا.",prefer_or:"تفضل [DRINKS] أم [DRINKS]؟"},
  hi:{flirty_hello:"[GREETING], आज रात तुम सचमुच [COMPLIMENT] लग रही हो.",warm_hello:"[GREETING], तुमसे मिलकर अच्छा लगा. बहुत [COMPLIMENT].",ask_drinks:"आपको कौन सी [DRINKS] पसंद है?",like_most:"मुझे [DRINKS] सबसे ज्यादा पसंद है, बहुत [ADJ_TASTE].",smile_compliment:"तुम्हारी मुस्कान [COMPLIMENT] है.",try_food:"यहाँ का [FOOD] ट्राई करें?",after_dinner:"खाने के बाद, [DESSERT] लें?",polite_help:"[GREETING], क्या आप मेरी मदद कर सकते हैं?",where_place:"सबसे नजदीकी [PLACE] कहाँ है?",order_drink:"मुझे [DRINKS] चाहिए.",city_is:"यह शहर बहुत [ADJ_TASTE] है.",formal_thanks:"[GREETING], आज आपके समय के लिए धन्यवाद.",offer_drink:"क्या मैं आपको [DRINKS] ऑफर कर सकता हूँ?",continue_over:"[FOOD] खाते हुए आगे बढ़ें?",good_to_see:"[GREETING]! आपसे मिलकर बहुत अच्छा लगा.",food_is:"यह [FOOD] बहुत [ADJ_TASTE] है.",nice_to_meet:"[GREETING], आपसे मिलकर खुशी हुई.",prefer_or:"आपको [DRINKS] पसंद है या [DRINKS]?"},
  pt:{flirty_hello:"[GREETING], você está realmente [COMPLIMENT] esta noite.",warm_hello:"[GREETING], que bom te ver. Você está [COMPLIMENT].",ask_drinks:"Que tipo de [DRINKS] você gosta?",like_most:"Eu gosto mais de [DRINKS], é muito [ADJ_TASTE].",smile_compliment:"Seu sorriso é muito [COMPLIMENT].",try_food:"Vamos experimentar a [FOOD] aqui?",after_dinner:"Depois do jantar, um [DESSERT]?",polite_help:"[GREETING], poderia me ajudar?",where_place:"Onde fica o [PLACE] mais próximo?",order_drink:"Eu gostaria de um [DRINKS], por favor.",city_is:"Esta cidade é muito [ADJ_TASTE].",formal_thanks:"[GREETING], obrigado pelo seu tempo hoje.",offer_drink:"Posso oferecer um [DRINKS]?",continue_over:"Vamos continuar com uma [FOOD]?",good_to_see:"[GREETING]! Que bom te ver.",food_is:"Esta [FOOD] está muito [ADJ_TASTE].",nice_to_meet:"[GREETING], prazer em conhecer.",prefer_or:"Você prefere [DRINKS] ou [DRINKS]?"},
  de:{flirty_hello:"[GREETING], du siehst heute Abend wirklich [COMPLIMENT] aus.",warm_hello:"[GREETING], schön dich zu sehen. Du siehst [COMPLIMENT] aus.",ask_drinks:"Was für ein [DRINKS] magst du?",like_most:"Ich mag [DRINKS] am liebsten — sehr [ADJ_TASTE].",smile_compliment:"Dein Lächeln ist wirklich [COMPLIMENT].",try_food:"Sollen wir die [FOOD] hier probieren?",after_dinner:"Nach dem Essen, ein [DESSERT]?",polite_help:"[GREETING], könnten Sie mir helfen?",where_place:"Wo ist das nächste [PLACE]?",order_drink:"Ich hätte gern ein [DRINKS], bitte.",city_is:"Diese Stadt ist wirklich [ADJ_TASTE].",formal_thanks:"[GREETING], danke für Ihre Zeit heute.",offer_drink:"Darf ich Ihnen ein [DRINKS] anbieten?",continue_over:"Machen wir weiter bei einer [FOOD]?",good_to_see:"[GREETING]! Schön dich zu sehen.",food_is:"Diese [FOOD] ist sehr [ADJ_TASTE].",nice_to_meet:"[GREETING], freut mich.",prefer_or:"Magst du lieber [DRINKS] oder [DRINKS]?"},
  ru:{flirty_hello:"[GREETING], ты сегодня выглядишь очень [COMPLIMENT].",warm_hello:"[GREETING], рад тебя видеть. Ты [COMPLIMENT].",ask_drinks:"Какой [DRINKS] тебе нравится?",like_most:"Мне больше всего нравится [DRINKS] — очень [ADJ_TASTE].",smile_compliment:"Твоя улыбка очень [COMPLIMENT].",try_food:"Попробуем [FOOD] здесь?",after_dinner:"После ужина, [DESSERT]?",polite_help:"[GREETING], не могли бы вы мне помочь?",where_place:"Где ближайший [PLACE]?",order_drink:"Мне [DRINKS], пожалуйста.",city_is:"Этот город очень [ADJ_TASTE].",formal_thanks:"[GREETING], спасибо за ваше время сегодня.",offer_drink:"Могу я предложить вам [DRINKS]?",continue_over:"Продолжим за [FOOD]?",good_to_see:"[GREETING]! Рад тебя видеть.",food_is:"Эта [FOOD] очень [ADJ_TASTE].",nice_to_meet:"[GREETING], приятно познакомиться.",prefer_or:"Ты предпочитаешь [DRINKS] или [DRINKS]?"},
  th:{flirty_hello:"[GREETING] คืนนี้คุณ[COMPLIMENT]มากเลย",warm_hello:"[GREETING] ดีใจที่ได้เจอ คุณ[COMPLIMENT]มาก",ask_drinks:"คุณชอบ[DRINKS]แบบไหนคะ?",like_most:"ผมชอบ[DRINKS]ที่สุด [ADJ_TASTE]มาก",smile_compliment:"รอยยิ้มของคุณ[COMPLIMENT]มาก",try_food:"ลอง[FOOD]ที่นี่ไหม?",after_dinner:"หลังอาหาร เอา[DESSERT]ไหม?",polite_help:"[GREETING] ช่วยผมหน่อยได้ไหม?",where_place:"[PLACE]ที่ใกล้ที่สุดอยู่ไหน?",order_drink:"ขอ[DRINKS]ครับ",city_is:"เมืองนี้[ADJ_TASTE]มาก",formal_thanks:"[GREETING] ขอบคุณสำหรับเวลาวันนี้",offer_drink:"ขอเสนอ[DRINKS]ได้ไหม?",continue_over:"คุยต่อระหว่างทาน[FOOD]ไหม?",good_to_see:"[GREETING]! ดีใจที่ได้เจอ",food_is:"[FOOD]นี้[ADJ_TASTE]มาก",nice_to_meet:"[GREETING] ยินดีที่ได้รู้จัก",prefer_or:"คุณชอบ[DRINKS]หรือ[DRINKS]?"},
  tr:{flirty_hello:"[GREETING], bu gece gerçekten [COMPLIMENT] görünüyorsun.",warm_hello:"[GREETING], seni görmek ne güzel. [COMPLIMENT] görünüyorsun.",ask_drinks:"Ne tür [DRINKS] seversin?",like_most:"En çok [DRINKS] severim, çok [ADJ_TASTE].",smile_compliment:"Gülümsemen gerçekten [COMPLIMENT].",try_food:"Buradaki [FOOD]'yı deneyelim mi?",after_dinner:"Yemekten sonra [DESSERT] ister misin?",polite_help:"[GREETING], bana yardım edebilir misiniz?",where_place:"En yakın [PLACE] nerede?",order_drink:"Bir [DRINKS] alabilir miyim, lütfen.",city_is:"Bu şehir gerçekten [ADJ_TASTE].",formal_thanks:"[GREETING], bugün zaman ayırdığınız için teşekkürler.",offer_drink:"Size bir [DRINKS] ikram edebilir miyim?",continue_over:"[FOOD] yiyerek devam edelim mi?",good_to_see:"[GREETING]! Seni görmek ne güzel.",food_is:"Bu [FOOD] çok [ADJ_TASTE].",nice_to_meet:"[GREETING], tanıştığıma memnun oldum.",prefer_or:"[DRINKS] mı yoksa [DRINKS] mı tercih edersin?"},
  vi:{flirty_hello:"[GREETING], tối nay bạn trông thật [COMPLIMENT].",warm_hello:"[GREETING], rất vui được gặp bạn. Bạn trông [COMPLIMENT] quá.",ask_drinks:"Bạn thích loại [DRINKS] nào?",like_most:"Mình thích [DRINKS] nhất — rất [ADJ_TASTE].",smile_compliment:"Nụ cười của bạn thật [COMPLIMENT].",try_food:"Mình thử [FOOD] ở đây nhé?",after_dinner:"Sau bữa tối, dùng [DESSERT] nhé?",polite_help:"[GREETING], bạn có thể giúp mình không?",where_place:"[PLACE] gần nhất ở đâu?",order_drink:"Cho mình một [DRINKS] nhé.",city_is:"Thành phố này thật [ADJ_TASTE].",formal_thanks:"[GREETING], cảm ơn bạn đã dành thời gian hôm nay.",offer_drink:"Mình mời bạn [DRINKS] nhé?",continue_over:"Mình vừa ăn [FOOD] vừa nói tiếp nhé?",good_to_see:"[GREETING]! Rất vui được gặp bạn.",food_is:"Món [FOOD] này rất [ADJ_TASTE].",nice_to_meet:"[GREETING], rất vui được gặp bạn.",prefer_or:"Bạn thích [DRINKS] hay [DRINKS]?"},
  tl:{flirty_hello:"[GREETING], ang [COMPLIMENT] mo naman ngayong gabi.",warm_hello:"[GREETING], masaya akong makita ka. Ang [COMPLIMENT] mo.",ask_drinks:"Anong klaseng [DRINKS] ang gusto mo?",like_most:"Mas gusto ko yung [DRINKS], sobrang [ADJ_TASTE].",smile_compliment:"Ang ngiti mo sobrang [COMPLIMENT].",try_food:"Subukan natin yung [FOOD] dito?",after_dinner:"Pagkatapos kumain, gusto mo ng [DESSERT]?",polite_help:"[GREETING], pwede mo ba akong tulungan?",where_place:"Nasaan ang pinakamalapit na [PLACE]?",order_drink:"Gusto ko ng [DRINKS], please.",city_is:"Ang lungsod na ito ay sobrang [ADJ_TASTE].",formal_thanks:"[GREETING], salamat sa oras mo ngayon.",offer_drink:"Gusto mo ba ng [DRINKS]?",continue_over:"Ituloy natin habang kumakain ng [FOOD]?",good_to_see:"[GREETING]! Masaya akong makita ka.",food_is:"Ang [FOOD] na ito ay sobrang [ADJ_TASTE].",nice_to_meet:"[GREETING], masaya akong makilala ka.",prefer_or:"Mas gusto mo [DRINKS] o [DRINKS]?"},
  nl:{flirty_hello:"[GREETING], je ziet er vanavond echt [COMPLIMENT] uit.",warm_hello:"[GREETING], leuk je te zien. Je ziet er [COMPLIMENT] uit.",ask_drinks:"Wat voor [DRINKS] vind je lekker?",like_most:"Ik vind [DRINKS] het lekkerst — heel [ADJ_TASTE].",smile_compliment:"Je lach is echt [COMPLIMENT].",try_food:"Zullen we de [FOOD] hier proberen?",after_dinner:"Na het eten, een [DESSERT]?",polite_help:"[GREETING], kunt u mij helpen?",where_place:"Waar is het dichtstbijzijnde [PLACE]?",order_drink:"Ik wil graag een [DRINKS], alstublieft.",city_is:"Deze stad is echt [ADJ_TASTE].",formal_thanks:"[GREETING], bedankt voor uw tijd vandaag.",offer_drink:"Mag ik u een [DRINKS] aanbieden?",continue_over:"Gaan we verder bij een [FOOD]?",good_to_see:"[GREETING]! Leuk je te zien.",food_is:"Deze [FOOD] is heel [ADJ_TASTE].",nice_to_meet:"[GREETING], aangenaam.",prefer_or:"Heb je liever [DRINKS] of [DRINKS]?"},
  sv:{flirty_hello:"[GREETING], du ser verkligen [COMPLIMENT] ut ikväll.",warm_hello:"[GREETING], kul att se dig. Du ser [COMPLIMENT] ut.",ask_drinks:"Vilken typ av [DRINKS] gillar du?",like_most:"Jag gillar [DRINKS] mest — väldigt [ADJ_TASTE].",smile_compliment:"Ditt leende är verkligen [COMPLIMENT].",try_food:"Ska vi prova [FOOD] här?",after_dinner:"Efter middagen, en [DESSERT]?",polite_help:"[GREETING], kan du hjälpa mig?",where_place:"Var ligger närmaste [PLACE]?",order_drink:"Jag vill ha en [DRINKS], tack.",city_is:"Den här staden är verkligen [ADJ_TASTE].",formal_thanks:"[GREETING], tack för din tid idag.",offer_drink:"Får jag bjuda dig på en [DRINKS]?",continue_over:"Ska vi fortsätta över en [FOOD]?",good_to_see:"[GREETING]! Kul att se dig.",food_is:"Den här [FOOD] är väldigt [ADJ_TASTE].",nice_to_meet:"[GREETING], trevligt att träffas.",prefer_or:"Föredrar du [DRINKS] eller [DRINKS]?"},
  pl:{flirty_hello:"[GREETING], wyglądasz dziś naprawdę [COMPLIMENT].",warm_hello:"[GREETING], miło cię widzieć. Wyglądasz [COMPLIMENT].",ask_drinks:"Jaki [DRINKS] lubisz?",like_most:"Najbardziej lubię [DRINKS] — bardzo [ADJ_TASTE].",smile_compliment:"Twój uśmiech jest naprawdę [COMPLIMENT].",try_food:"Spróbujemy [FOOD] tutaj?",after_dinner:"Po kolacji, może [DESSERT]?",polite_help:"[GREETING], czy mógłby pan mi pomóc?",where_place:"Gdzie jest najbliższy [PLACE]?",order_drink:"Poproszę [DRINKS].",city_is:"To miasto jest naprawdę [ADJ_TASTE].",formal_thanks:"[GREETING], dziękuję za pański czas.",offer_drink:"Czy mogę zaproponować [DRINKS]?",continue_over:"Kontynuujmy przy [FOOD]?",good_to_see:"[GREETING]! Miło cię widzieć.",food_is:"To [FOOD] jest bardzo [ADJ_TASTE].",nice_to_meet:"[GREETING], miło poznać.",prefer_or:"Wolisz [DRINKS] czy [DRINKS]?"},
  bg:{flirty_hello:"[GREETING], изглеждаш наистина [COMPLIMENT] тази вечер.",warm_hello:"[GREETING], приятно ми е да се запознаем. Изглеждаш [COMPLIMENT].",ask_drinks:"Какъв вид [DRINKS] харесваш?",like_most:"Най-много харесвам [DRINKS] — много [ADJ_TASTE].",smile_compliment:"Усмивката ти е толкова [COMPLIMENT].",try_food:"Искаш ли да опиташ [FOOD] тук?",after_dinner:"След вечеря, какво ще кажеш за [DESSERT]?",polite_help:"[GREETING], можеш ли да ми помогнеш?",where_place:"Къде е най-близкият [PLACE]?",order_drink:"Бих искал [DRINKS], моля.",city_is:"Този град е наистина [ADJ_TASTE].",formal_thanks:"[GREETING], благодаря за отделеното време днес.",offer_drink:"Мога ли да ти предложа [DRINKS]?",continue_over:"Нека продължим с [FOOD].",good_to_see:"[GREETING]! Радвам се да те видя.",food_is:"Тази [FOOD] е много [ADJ_TASTE].",nice_to_meet:"[GREETING], приятно ми е.",prefer_or:"Предпочиташ [DRINKS] или [DRINKS]?"}
};

// ── Romanized templates for non-Latin scripts ──

export const TR_ROM: Record<string, Record<PhraseKey, string>> = {
  ja:{flirty_hello:"[GREETING], konya wa totemo [COMPLIMENT] desu ne.",warm_hello:"[GREETING], aete ureshii desu. Totemo [COMPLIMENT].",ask_drinks:"Donna [DRINKS] ga suki desu ka?",like_most:"[DRINKS] ga ichiban suki desu. Totemo [ADJ_TASTE].",smile_compliment:"Anata no egao, hontou ni [COMPLIMENT].",try_food:"Koko no [FOOD], tabete mimasen ka?",after_dinner:"Shokuji no ato, [DESSERT] dou?",polite_help:"[GREETING], tetsudatte itadakemasu ka?",where_place:"Ichiban chikai [PLACE] wa doko desu ka?",order_drink:"[DRINKS] wo kudasai.",city_is:"Kono machi, totemo [ADJ_TASTE].",formal_thanks:"[GREETING], honjitsu wa ojikan wo arigatou gozaimasu.",offer_drink:"[DRINKS] wa ikaga desu ka?",continue_over:"[FOOD] wo tabenagara tsuzukemashou ka?",good_to_see:"[GREETING]! Aete ureshii.",food_is:"Kono [FOOD], totemo [ADJ_TASTE].",nice_to_meet:"[GREETING], hajimemashite.",prefer_or:"[DRINKS] to [DRINKS], docchi ga suki?"},
  zh:{flirty_hello:"[GREETING], nǐ jīnwǎn zhēn de hěn [COMPLIMENT].",warm_hello:"[GREETING], jiàn dào nǐ zhēn gāoxìng. Nǐ hěn [COMPLIMENT].",ask_drinks:"Nǐ xǐhuān shénme yàng de [DRINKS]?",like_most:"Wǒ zuì xǐhuān [DRINKS], fēicháng [ADJ_TASTE].",smile_compliment:"Nǐ de xiàoróng zhēn de hěn [COMPLIMENT].",try_food:"Wǒmen shìshi zhèlǐ de [FOOD] ba?",after_dinner:"Chī wán fàn hòu, yào bù yào lái gè [DESSERT]?",polite_help:"[GREETING], nǐ néng bāng bāng wǒ ma?",where_place:"Zuìjìn de [PLACE] zài nǎlǐ?",order_drink:"Wǒ yào yī bēi [DRINKS], xièxie.",city_is:"Zhège chéngshì zhēn de hěn [ADJ_TASTE].",formal_thanks:"[GREETING], gǎnxiè nín jīntiān de shíjiān.",offer_drink:"Wǒ kěyǐ qǐng nǐ hē [DRINKS] ma?",continue_over:"Wǒmen biān chī [FOOD] biān jìxù ba?",good_to_see:"[GREETING]! Jiàn dào nǐ zhēn gāoxìng.",food_is:"Zhège [FOOD] fēicháng [ADJ_TASTE].",nice_to_meet:"[GREETING], hěn gāoxìng rènshi nǐ.",prefer_or:"Nǐ gèng xǐhuān [DRINKS] háishì [DRINKS]?"},
  ko:{flirty_hello:"[GREETING], oneul bam jeongmal [COMPLIMENT]-ieyo.",warm_hello:"[GREETING], mannaseo bangawoyo. [COMPLIMENT]-ieyo.",ask_drinks:"Eotteon [DRINKS]-reul joahaseyo?",like_most:"[DRINKS]-ga jeil joayo, jeongmal [ADJ_TASTE]-haeyo.",smile_compliment:"Misoga jeongmal [COMPLIMENT]-ieyo.",try_food:"Yeogi [FOOD] meogeobolkkayo?",after_dinner:"Siksa hue [DESSERT] eottaeyo?",polite_help:"[GREETING], jom dowajusil su isseulkkayo?",where_place:"Gajang gakkaun [PLACE]-i eodi-yeyo?",order_drink:"[DRINKS] juseyo.",city_is:"I dosi jeongmal [ADJ_TASTE]-ieyo.",formal_thanks:"[GREETING], oneul sigan naejusyeoseo gamsahamnida.",offer_drink:"[DRINKS] han jan hasigesseoyo?",continue_over:"[FOOD] meogeumyeonseo gyesok halkkayo?",good_to_see:"[GREETING]! Mannaseo bangawoyo.",food_is:"I [FOOD] jeongmal [ADJ_TASTE]-ieyo.",nice_to_meet:"[GREETING], bangapseumnida.",prefer_or:"[DRINKS]-wa [DRINKS] junge mwoga joeusaeyo?"},
  ar:{flirty_hello:"[GREETING], anti fi'lan [COMPLIMENT] al-layla.",warm_hello:"[GREETING], sa'iid biliqaa'ik. Anti [COMPLIMENT].",ask_drinks:"Ayy naw' min [DRINKS] tufaddiliin?",like_most:"Afdal [DRINKS], ta'muhu [ADJ_TASTE] jiddan.",smile_compliment:"Ibtisaamatuk [COMPLIMENT] jiddan.",try_food:"Hal nujarrib [FOOD] huna?",after_dinner:"Ba'd al-'asha', [DESSERT]?",polite_help:"[GREETING], hal yumkinuk musa'adati?",where_place:"Ayna aqrab [PLACE]?",order_drink:"Uriid [DRINKS] min fadlak.",city_is:"Hadhihi al-madiina [ADJ_TASTE] jiddan.",formal_thanks:"[GREETING], shukran 'ala waqtik al-yawm.",offer_drink:"Hal uqaddim lak [DRINKS]?",continue_over:"Hal nukmil ma' [FOOD]?",good_to_see:"[GREETING]! Sa'iid biliqaa'ik.",food_is:"Hadha [FOOD] [ADJ_TASTE] jiddan.",nice_to_meet:"[GREETING], tasharrafna.",prefer_or:"Tufaddil [DRINKS] am [DRINKS]?"},
  hi:{flirty_hello:"[GREETING], aaj raat tum sachmuch [COMPLIMENT] lag rahi ho.",warm_hello:"[GREETING], tumse milkar achha laga. Bahut [COMPLIMENT].",ask_drinks:"Aapko kaun si [DRINKS] pasand hai?",like_most:"Mujhe [DRINKS] sabse zyada pasand hai, bahut [ADJ_TASTE].",smile_compliment:"Tumhari muskaan [COMPLIMENT] hai.",try_food:"Yahan ka [FOOD] try karein?",after_dinner:"Khaane ke baad, [DESSERT] lein?",polite_help:"[GREETING], kya aap meri madad kar sakte hain?",where_place:"Sabse nazdeeki [PLACE] kahan hai?",order_drink:"Mujhe [DRINKS] chahiye.",city_is:"Yah shahar bahut [ADJ_TASTE] hai.",formal_thanks:"[GREETING], aaj aapke samay ke liye dhanyavaad.",offer_drink:"Kya main aapko [DRINKS] offer kar sakta hoon?",continue_over:"[FOOD] khaate hue aage badhein?",good_to_see:"[GREETING]! Aapse milkar bahut achha laga.",food_is:"Yah [FOOD] bahut [ADJ_TASTE] hai.",nice_to_meet:"[GREETING], aapse milkar khushi hui.",prefer_or:"Aapko [DRINKS] pasand hai ya [DRINKS]?"},
  ru:{flirty_hello:"[GREETING], ty segodnya vyglyadish ochen' [COMPLIMENT].",warm_hello:"[GREETING], rad tebya videt'. Ty [COMPLIMENT].",ask_drinks:"Kakoy [DRINKS] tebe nravitsya?",like_most:"Mne bol'she vsego nravitsya [DRINKS] — ochen' [ADJ_TASTE].",smile_compliment:"Tvoya ulybka ochen' [COMPLIMENT].",try_food:"Poprobuem [FOOD] zdes'?",after_dinner:"Posle uzhina, [DESSERT]?",polite_help:"[GREETING], ne mogli by vy mne pomoch'?",where_place:"Gde blizhayshiy [PLACE]?",order_drink:"Mne [DRINKS], pozhaluysta.",city_is:"Etot gorod ochen' [ADJ_TASTE].",formal_thanks:"[GREETING], spasibo za vashe vremya segodnya.",offer_drink:"Mogu ya predlozhit' vam [DRINKS]?",continue_over:"Prodolzhim za [FOOD]?",good_to_see:"[GREETING]! Rad tebya videt'.",food_is:"Eta [FOOD] ochen' [ADJ_TASTE].",nice_to_meet:"[GREETING], priyatno poznakomit'sya.",prefer_or:"Ty predpochitaesh' [DRINKS] ili [DRINKS]?"},
  th:{flirty_hello:"[GREETING] khuun nii khun [COMPLIMENT] maak loei.",warm_hello:"[GREETING] diijai thii dai joer. Khun [COMPLIMENT] maak.",ask_drinks:"Khun chawp [DRINKS] baep nai kha?",like_most:"Phom chawp [DRINKS] thii sut, [ADJ_TASTE] maak.",smile_compliment:"Roi yim khawng khun [COMPLIMENT] maak.",try_food:"Lawng [FOOD] thii nii mai?",after_dinner:"Lang aahaan, ao [DESSERT] mai?",polite_help:"[GREETING] chuay phom noi dai mai?",where_place:"[PLACE] thii glai thii sut yuu nai?",order_drink:"Khor [DRINKS] khrap.",city_is:"Mueang nii [ADJ_TASTE] maak.",formal_thanks:"[GREETING] khawp khun samrap welaa wan nii.",offer_drink:"Khor sanoe [DRINKS] dai mai?",continue_over:"Khuy taw rahwang thaan [FOOD] mai?",good_to_see:"[GREETING]! Diijai thii dai joer.",food_is:"[FOOD] nii [ADJ_TASTE] maak.",nice_to_meet:"[GREETING] yindii thii dai ruujak.",prefer_or:"Khun chawp [DRINKS] rue [DRINKS]?"},
  bg:{flirty_hello:"[GREETING], izglezhdash naistina [COMPLIMENT] tazi vecher.",warm_hello:"[GREETING], priyatno mi e da se zapoznaem. Izglezhdash [COMPLIMENT].",ask_drinks:"Kakav vid [DRINKS] kharesvash?",like_most:"Nay-mnogo kharesvam [DRINKS] — mnogo [ADJ_TASTE].",smile_compliment:"Usmivkata ti e tolkova [COMPLIMENT].",try_food:"Iskash li da opitash [FOOD] tuk?",after_dinner:"Sled vecherya, kakvo shte kazhesh za [DESSERT]?",polite_help:"[GREETING], mozhesh li da mi pomoghesh?",where_place:"Kade e nay-blizkiyat [PLACE]?",order_drink:"Bikh iskal [DRINKS], molya.",city_is:"Tozi grad e naistina [ADJ_TASTE].",formal_thanks:"[GREETING], blagodarya za otdelenoto vreme dnes.",offer_drink:"Moga li da ti predlozha [DRINKS]?",continue_over:"Neka prodalzhim s [FOOD].",good_to_see:"[GREETING]! Radvam se da te vidya.",food_is:"Tazi [FOOD] e mnogo [ADJ_TASTE].",nice_to_meet:"[GREETING], priyatno mi e.",prefer_or:"Predpochitash [DRINKS] ili [DRINKS]?"}
};


// ── Phonetic pronunciation templates (syllable·broken pronunciation guides) ──
// Uses · between syllables to help learners sound out phrases
export const TR_PHON: Record<string, Record<PhraseKey, string>> = {
  ja:{flirty_hello:"[GREETING], kyoh·wah hohn·toh·nee [COMPLIMENT] deh·su·neh.",warm_hello:"[GREETING], ah·eh·teh oo·reh·shee deh·su. toh·teh·moh [COMPLIMENT].",ask_drinks:"dohn·nah [DRINKS] gah soo·kee deh·su·kah?",like_most:"[DRINKS] gah ee·chee·bahn soo·kee deh·su — toh·teh·moh [ADJ_TASTE].",smile_compliment:"ah·nah·tah·noh eh·gah·oh, hohn·toh·nee [COMPLIMENT].",try_food:"koh·koh·noh [FOOD], tah·beh·teh mee·mah·sehn·kah?",after_dinner:"shoh·koo·jee·noh ah·toh, [DESSERT] doh?",polite_help:"[GREETING], teh·tsu·daht·teh ee·tah·dah·keh·mah·su·kah?",where_place:"ee·chee·bahn chee·kah·ee [PLACE] wah doh·koh deh·su·kah?",order_drink:"[DRINKS] oh koo·dah·sah·ee.",city_is:"koh·noh mah·chee, toh·teh·moh [ADJ_TASTE].",formal_thanks:"[GREETING], hohn·jee·tsu wah oh·jee·kahn oh ah·ree·gah·toh goh·zah·ee·mah·su.",offer_drink:"[DRINKS] wah ee·kah·gah deh·su·kah?",continue_over:"[FOOD] oh tah·beh·nah·gah·rah tsoo·zoo·keh·mah·shoh·kah?",good_to_see:"[GREETING]! ah·eh·teh oo·reh·shee.",food_is:"koh·noh [FOOD], toh·teh·moh [ADJ_TASTE].",nice_to_meet:"[GREETING], hah·jee·meh·mah·shee·teh.",prefer_or:"[DRINKS] toh [DRINKS], doh·chee·rah gah soo·kee?"},
  zh:{flirty_hello:"[GREETING], nee jeen·wahn jehn·duh hahn [COMPLIMENT].",warm_hello:"[GREETING], jyehn·dow nee jehn gow·sheeng. nee hahn [COMPLIMENT].",ask_drinks:"nee shee·hwahn shuh·muh [DRINKS]?",like_most:"woh zweh shee·hwahn [DRINKS], fay·chahng [ADJ_TASTE].",smile_compliment:"nee·duh shyow·rohng jehn·duh hahn [COMPLIMENT].",try_food:"woh·mehn shih·shih jeh·lee·duh [FOOD] bah?",after_dinner:"chr·wahn fahn·how, yow·boo·yow lye·guh [DESSERT]?",polite_help:"[GREETING], nee nuhng bahng·bahng woh mah?",where_place:"zweh·jeen·duh [PLACE] zai nah·lee?",order_drink:"woh yow yee·bay [DRINKS], shyeh·shyeh.",city_is:"jeh·guh chuhng·shih jehn·duh hahn [ADJ_TASTE].",formal_thanks:"[GREETING], gahn·shyeh neen jeen·tyehn·duh shih·jyehn.",offer_drink:"woh kuh·yee cheeng nee huh [DRINKS] mah?",continue_over:"woh·mehn byehn chr [FOOD] byehn jee·shoo bah?",good_to_see:"[GREETING]! jyehn·dow nee jehn gow·sheeng.",food_is:"jeh·guh [FOOD] fay·chahng [ADJ_TASTE].",nice_to_meet:"[GREETING], hahn gow·sheeng rehn·shih nee.",prefer_or:"nee guhng shee·hwahn [DRINKS] hai·shih [DRINKS]?"},
  ko:{flirty_hello:"[GREETING], oh·neul jahng·mahl [COMPLIMENT]·ee·eh·yoh.",warm_hello:"[GREETING], mahn·nah·suh bahn·gah·wuh·yoh. [COMPLIMENT]·ee·eh·yoh.",ask_drinks:"uh·ttuhn [DRINKS]·reul joh·ah·hah·seh·yoh?",like_most:"[DRINKS]·gah jeh·eel joh·ah·yoh, juhng·mahl [ADJ_TASTE]·heh·yoh.",smile_compliment:"mee·soh·gah juhng·mahl [COMPLIMENT]·ee·eh·yoh.",try_food:"yuh·gee [FOOD] muh·guh·bohl·kkah·yoh?",after_dinner:"sheek·sah·hweh [DESSERT] uh·tteh·yoh?",polite_help:"[GREETING], johm doh·wah·joo·sheel·soo ees·seul·kkah·yoh?",where_place:"gah·jahng gah·kkah·oon [PLACE]·ee uh·dee·yeh·yoh?",order_drink:"[DRINKS] joo·seh·yoh.",city_is:"ee doh·shee juhng·mahl [ADJ_TASTE]·ee·eh·yoh.",formal_thanks:"[GREETING], oh·neul shee·gahn nay·joo·shyuh·suh gahm·sah·hahm·nee·dah.",offer_drink:"[DRINKS] hahn·jahn hah·shee·geh·ssuh·yoh?",continue_over:"[FOOD] muh·geu·myuhn·suh gyeh·sohk hahl·kkah·yoh?",good_to_see:"[GREETING]! mahn·nah·suh bahn·gah·wuh·yoh.",food_is:"ee [FOOD] juhng·mahl [ADJ_TASTE]·ee·eh·yoh.",nice_to_meet:"[GREETING], bahn·gahp·seum·nee·dah.",prefer_or:"[DRINKS]·wah [DRINKS] joong·eh mwoh·gah duh joh·eu·seh·yoh?"},
  ru:{flirty_hello:"[GREETING], tih see·vohd·nyah vih·glyah·deesh oh·chehn [COMPLIMENT].",warm_hello:"[GREETING], rahd tyeh·byah vee·dyeht. tih [COMPLIMENT].",ask_drinks:"kah·koy [DRINKS] tyeh·byeh nrah·veet·syah?",like_most:"mnyeh bohl·sheh vsyeh·goh nrah·veet·syah [DRINKS] — oh·chehn [ADJ_TASTE].",smile_compliment:"tvah·yah oo·lihb·kah oh·chehn [COMPLIMENT].",try_food:"pah·proh·boo·yehm [FOOD] zdyehs?",after_dinner:"pohs·lyeh oo·zhee·nah, [DESSERT]?",polite_help:"[GREETING], nyeh mahg·lee bih vih mnyeh pah·mohch?",where_place:"gdyeh blee·zhai·shee [PLACE]?",order_drink:"mnyeh [DRINKS], pah·zhah·loo·stah.",city_is:"eh·taht goh·ruhd oh·chehn [ADJ_TASTE].",formal_thanks:"[GREETING], spah·see·boh zah vah·sheh vryeh·myah syeh·vohd·nyah.",offer_drink:"mah·goo yah pryehd·lah·zhiht vahm [DRINKS]?",continue_over:"prahd·ohl·zheem zah [FOOD]?",good_to_see:"[GREETING]! rahd tyeh·byah vee·dyeht.",food_is:"eh·tah [FOOD] oh·chehn [ADJ_TASTE].",nice_to_meet:"[GREETING], pree·yaht·nah pahz·nah·koh·meet·syah.",prefer_or:"tih pryehd·pah·chee·tah·yehsh [DRINKS] ee·lee [DRINKS]?"},
  ar:{flirty_hello:"[GREETING], een·tee ahl·yohm [COMPLIMENT] jid·dahn.",warm_hello:"[GREETING], sah·eed beel·ee·kah·eek. een·tee [COMPLIMENT].",ask_drinks:"ay noh meen [DRINKS] too·fahd·dee·leen?",like_most:"ahf·dahl [DRINKS], tahm·oo [ADJ_TASTE] jid·dahn.",smile_compliment:"eeb·tee·sah·mah·tek [COMPLIMENT] jid·dahn.",try_food:"hahl noo·jar·reeb [FOOD] hoo·nah?",after_dinner:"bahd ahl·ah·shah, [DESSERT]?",polite_help:"[GREETING], hahl yoom·kee·nook moo·sah·ah·dah·tee?",where_place:"ay·nah ahk·rahb [PLACE]?",order_drink:"oo·reed [DRINKS] meen fahd·lahk.",city_is:"hah·thee·hee ahl·mah·dee·nah [ADJ_TASTE] jid·dahn.",formal_thanks:"[GREETING], shook·rahn ah·lah wahk·tahk ahl·yohm.",offer_drink:"hahl oo·kahd·deem lahk [DRINKS]?",continue_over:"hahl nook·meel mah [FOOD]?",good_to_see:"[GREETING]! sah·eed beel·ee·kah·eek.",food_is:"hah·thah [FOOD] [ADJ_TASTE] jid·dahn.",nice_to_meet:"[GREETING], tah·shah·raf·nah.",prefer_or:"too·fahd·deel [DRINKS] ahm [DRINKS]?"},
  hi:{flirty_hello:"[GREETING], aahj raht toom sahch·mooch [COMPLIMENT] lahg ruh·hee hoh.",warm_hello:"[GREETING], toom·seh mil·kahr ahch·chah luh·gah. buh·hoot [COMPLIMENT].",ask_drinks:"aahp·koh kown·see [DRINKS] puh·sahnd hai?",like_most:"moo·jheh [DRINKS] sub·seh zyah·dah puh·sahnd hai, buh·hoot [ADJ_TASTE].",smile_compliment:"toom·hah·ree moos·kahn [COMPLIMENT] hai.",try_food:"yuh·hahn kah [FOOD] trai kuh·rein?",after_dinner:"khah·neh keh baahd, [DESSERT] lein?",polite_help:"[GREETING], kyah aahp meh·ree muh·duhd kuhr suhk·teh hain?",where_place:"sub·seh nuz·dee·kee [PLACE] kuh·hahn hai?",order_drink:"moo·jheh [DRINKS] chah·hee·yeh.",city_is:"yeh shuh·huhr buh·hoot [ADJ_TASTE] hai.",formal_thanks:"[GREETING], aahj aahp·keh suh·mai keh lee·yeh dhun·yuh·vaahd.",offer_drink:"kyah main aahp·koh [DRINKS] ohf·fuhr kuhr suhk·tah hoon?",continue_over:"[FOOD] khah·teh hoo·eh aah·geh buh·dhein?",good_to_see:"[GREETING]! aahp·seh mil·kuhr buh·hoot ahch·chah luh·gah.",food_is:"yeh [FOOD] buh·hoot [ADJ_TASTE] hai.",nice_to_meet:"[GREETING], aahp·seh mil·kuhr khoo·shee hoo·ee.",prefer_or:"aahp·koh [DRINKS] puh·sahnd hai yah [DRINKS]?"},
  th:{flirty_hello:"[GREETING] koon·nee koon [COMPLIMENT] mahk luh·ee.",warm_hello:"[GREETING] dee·jai tee·dai·juh. koon [COMPLIMENT] mahk.",ask_drinks:"koon chawp [DRINKS] baep nai kah?",like_most:"pohm chawp [DRINKS] tee·soot, [ADJ_TASTE] mahk.",smile_compliment:"roi·yim·kawng·koon [COMPLIMENT] mahk.",try_food:"lawng [FOOD] tee·nee mai?",after_dinner:"lahng·ah·hahn, ow [DESSERT] mai?",polite_help:"[GREETING] choo·ay·noy·dai·mai?",where_place:"[PLACE] tee·glai·tee·soot yoo·tee·nai?",order_drink:"kawr [DRINKS] krahp.",city_is:"meu·ahng·nee [ADJ_TASTE] mahk.",formal_thanks:"[GREETING] kawp·koon·sahm·rahp·way·lah·wahn·nee.",offer_drink:"kawr·tahm [DRINKS] hai·dai·mai?",continue_over:"koo·ee·gahn·rawng [FOOD]·gahn·tuh.",good_to_see:"[GREETING]! dee·jai·tee·dai·juh.",food_is:"[FOOD]·nee [ADJ_TASTE] mahk.",nice_to_meet:"[GREETING] yin·dee·tee·dai·roo·jahk.",prefer_or:"koon chawp [DRINKS] reu [DRINKS]?"},
  bg:{flirty_hello:"[GREETING], eez·glehzh·dahsh nah·ees·tee·nah [COMPLIMENT] tah·zee veh·chehr.",warm_hello:"[GREETING], pree·yaht·noh mee eh dah seh zah·pohz·nah·ehm. eez·glehzh·dahsh [COMPLIMENT].",ask_drinks:"kah·kuhv veed [DRINKS] khah·rehs·vahsh?",like_most:"nai·mnoh·goh khah·rehs·vahm [DRINKS] — mnoh·goh [ADJ_TASTE].",smile_compliment:"oos·meev·kah·tah tee eh tohl·koh·vah [COMPLIMENT].",try_food:"ees·kahsh lee dah oh·pee·tahsh [FOOD] took?",after_dinner:"slehd veh·chehr·yah, kahk·voh kah·zhehsh zah [DESSERT]?",polite_help:"[GREETING], moh·zhehsh lee dah mee poh·mohg·nehsh?",where_place:"kuh·deh eh nai·bleez·kee·yaht [PLACE]?",order_drink:"beekh ees·kahl [DRINKS], mohl·yah.",city_is:"toh·zee grahd eh nah·ees·tee·nah [ADJ_TASTE].",formal_thanks:"[GREETING], blah·goh·dah·ryah zah vahs·heh·toh vreh·meh dnehs.",offer_drink:"moh·gah lee dah tee prehd·loh·zhah [DRINKS]?",continue_over:"neh·kah prahd·uhl·zheem suh [FOOD].",good_to_see:"[GREETING]! rahd·vahm seh dah teh vee·dyah.",food_is:"tah·zee [FOOD] eh mnoh·goh [ADJ_TASTE].",nice_to_meet:"[GREETING], pree·yaht·noh mee eh.",prefer_or:"prehd·poh·chee·tahsh [DRINKS] ee·lee [DRINKS]?"},
  es:{flirty_hello:"[GREETING], oy ehs·tahs reh·ahl·mehn·teh [COMPLIMENT].",warm_hello:"[GREETING], ehn·kahn·tah·doh deh koh·noh·sehr·teh. ehs·tahs [COMPLIMENT].",ask_drinks:"keh·tee·poh·deh [DRINKS] teh·goos·tah?",like_most:"meh·goos·tah·mahs [DRINKS] — mooy [ADJ_TASTE].",smile_compliment:"too·sohn·ree·sah ehs mooy [COMPLIMENT].",try_food:"kyeh·rehs proh·bahr·lah [FOOD] deh·ah·kee?",after_dinner:"dehs·pwehs deh·seh·nahr, keh·tahl [DESSERT]?",polite_help:"[GREETING], poh·dree·ahs ah·yoo·dahr·meh?",where_place:"dohn·deh ehs·tah ehl [PLACE] mahs·sehr·kah·noh?",order_drink:"meh·goos·tah·ree·ah oon [DRINKS], pohr·fah·vohr.",city_is:"ehs·tah syoo·dahd ehs mooy [ADJ_TASTE].",formal_thanks:"[GREETING], grah·syahs pohr soo tyehm·poh oy.",offer_drink:"pweh·doh oh·freh·sehr·teh oon [DRINKS]?",continue_over:"see·gah·mohs kohn [FOOD].",good_to_see:"[GREETING]! keh·goos·toh vehr·teh.",food_is:"ehs·tah [FOOD] ehs·tah mooy [ADJ_TASTE].",nice_to_meet:"[GREETING], mooy·choh goos·toh.",prefer_or:"preh·fyeh·rehs [DRINKS] oh [DRINKS]?"},
  fr:{flirty_hello:"[GREETING], too·eh vreh·mahn [COMPLIMENT] suh·swahr.",warm_hello:"[GREETING], rahn·shahn·teh. too·eh [COMPLIMENT].",ask_drinks:"kehl·suhr·duh [DRINKS] ehm·too?",like_most:"zhuh·preh·fehr·luh [DRINKS] — treh [ADJ_TASTE].",smile_compliment:"tohn·soo·reer·eh treh [COMPLIMENT].",try_food:"too·vuh·goo·tay·lah [FOOD] ee·see?",after_dinner:"ah·preh·luh·dee·nay, uhn [DESSERT]?",polite_help:"[GREETING], poo·ryeh·voo·meh·day?",where_place:"oo·ehl·luh [PLACE] luh·ploo·prohsh?",order_drink:"zhuh·voo·dreh uhn [DRINKS], seel·voo·pleh.",city_is:"seht·veel·eh vreh·mahn [ADJ_TASTE].",formal_thanks:"[GREETING], mehr·see·poor·voh·truh·tahn·oh·zhoor·dwee.",offer_drink:"pweezh·voo·zoh·freer uhn [DRINKS]?",continue_over:"kohn·tee·noo·ohn·oh·toor·duhn [FOOD].",good_to_see:"[GREETING]! kohn·tahn·duh·tuh·vwahr.",food_is:"seht [FOOD] eh treh [ADJ_TASTE].",nice_to_meet:"[GREETING], rahn·shahn·teh.",prefer_or:"too·preh·fehr [DRINKS] oo [DRINKS]?"},
  it:{flirty_hello:"[GREETING], stah·seh·rah shei dah·veh·roh [COMPLIMENT].",warm_hello:"[GREETING], pyah·cheh·reh dee koh·noh·shehr·tee. shei [COMPLIMENT].",ask_drinks:"keh·tee·poh dee [DRINKS] tee·pyah·cheh?",like_most:"mee·pyah·cheh dee pyoo [DRINKS] — mohl·toh [ADJ_TASTE].",smile_compliment:"eel too·oh sohr·ree·soh eh mohl·toh [COMPLIMENT].",try_food:"voo·oy ahs·sahj·jah·reh lah [FOOD] kwee?",after_dinner:"doh·poh cheh·nah, keh neh dee·chee dee [DESSERT]?",polite_help:"[GREETING], poh·trehs·tee ah·yoo·tahr·mee?",where_place:"doh·veh eel [PLACE] pyoo vee·chee·noh?",order_drink:"vohr·ray oon [DRINKS], pehr·fah·voh·reh.",city_is:"kwehs·tah cheet·tah eh dah·veh·roh [ADJ_TASTE].",formal_thanks:"[GREETING], grah·tsyeh pehr eel too·oh tehm·poh ohj·jee.",offer_drink:"pohs·soh ohf·freer·tee oon [DRINKS]?",continue_over:"kohn·tee·noo·yah·moh kohn [FOOD].",good_to_see:"[GREETING]! keh·pyah·cheh·reh veh·dehr·tee.",food_is:"kwehs·toh [FOOD] eh mohl·toh [ADJ_TASTE].",nice_to_meet:"[GREETING], pyah·cheh·reh dee koh·noh·shehr·tee.",prefer_or:"preh·feh·ree·shee [DRINKS] oh [DRINKS]?"},
  de:{flirty_hello:"[GREETING], doo zeest hoy·teh veer·kleech [COMPLIMENT].",warm_hello:"[GREETING], noi·seh deech kehn·ehn·tsoo·lehr·nehn. doo beest [COMPLIMENT].",ask_drinks:"vehl·cheh [DRINKS] mahgst·doo?",like_most:"eech·mahg [DRINKS] ahm·leeb·stehn — zehr [ADJ_TASTE].",smile_compliment:"dine·leh·cheln eest·zoh [COMPLIMENT].",try_food:"muhkh·test·doo dahs [FOOD] heer proh·bee·rehn?",after_dinner:"nahkh·dehm·eh·sehn, vee·vehr ehs meet [DESSERT]?",polite_help:"[GREETING], kuhn·tehn·zee meer·hel·fehn?",where_place:"voh·eest dahs·nekhs·teh [PLACE]?",order_drink:"eech·heht·teh·gehrn ai·nehn [DRINKS], bee·teh.",city_is:"dee·zeh·shtaht eest veer·kleech [ADJ_TASTE].",formal_thanks:"[GREETING], fee·lehn·dahnk fuer ee·reh·tsite hoy·teh.",offer_drink:"dahrf·eech ee·nehn ai·nehn [DRINKS] ahn·bee·tehn?",continue_over:"lahs·oons bai [FOOD] vai·ter·mahk·hehn.",good_to_see:"[GREETING]! shurn·deech tsoo·zay·ehn.",food_is:"dee·zehs [FOOD] eest·zehr [ADJ_TASTE].",nice_to_meet:"[GREETING], froy·t·meech.",prefer_or:"bee·for·tsoogst·doo [DRINKS] oh·dehr [DRINKS]?"},
  pt:{flirty_hello:"[GREETING], voh·seh ehs·tah heh·ahl·mehn·chee [COMPLIMENT] ohj.",warm_hello:"[GREETING], prah·zehr ehn koh·nyeh·sehr·voh·seh. voh·seh ehs·tah [COMPLIMENT].",ask_drinks:"keh·tee·poh deh [DRINKS] voh·seh gohs·tah?",like_most:"eh·oo gohs·toh mais deh [DRINKS] — moo·ee·toh [ADJ_TASTE].",smile_compliment:"seh·oo sohr·hee·zoh eh moo·ee·toh [COMPLIMENT].",try_food:"kehr ehs·peh·ree·mehn·tahr ah [FOOD] dah·kee?",after_dinner:"deh·poy doh jahn·tahr, keh·tahl [DESSERT]?",polite_help:"[GREETING], voh·seh poh·deh·ree·ah mee·ah·zhoo·dahr?",where_place:"ohn·deh fee·kah oh [PLACE] mais pehr·toh?",order_drink:"eh·oo gohs·tah·ree·ah deh oom [DRINKS], pohr·fah·vohr.",city_is:"ehs·tah see·dah·deh eh moo·ee·toh [ADJ_TASTE].",formal_thanks:"[GREETING], oh·bree·gah·doh peh·loo seh·oo tehn·poh ohj.",offer_drink:"poh·soh teh oh·feh·reh·sehr oom [DRINKS]?",continue_over:"vah·mohs kohn·tee·noo·ahr kohn [FOOD].",good_to_see:"[GREETING]! keh·bohm teh·vehr.",food_is:"ehs·tah [FOOD] ehs·tah moo·ee·toh [ADJ_TASTE].",nice_to_meet:"[GREETING], moo·ee·toh prah·zehr.",prefer_or:"voh·seh preh·feh·reh [DRINKS] oh [DRINKS]?"},
};

// ── Helper: get phrase in target language ──

export function langPhrase(lang: string, key: PhraseKey): string {
  return TR[lang]?.[key] ?? "[GREETING]";
}

export function langRom(lang: string, key: PhraseKey): string {
  return TR_ROM[lang]?.[key] ?? "";
}

/** Get phonetic pronunciation template for a phrase key */
export function langPhon(lang: string, key: PhraseKey): string {
  return TR_PHON[lang]?.[key] ?? "";
}

// ── Helper: get language display for glasses list ──

export function getLangListItems(): string[] {
  return LANG_CODES.map(code => `${LANG_FLAG[code]} ${LANG_LABEL[code]}`);
}
