// ═══════════════════════════════════════════════════════════════════
// Lingua Franca — Sprite Registry  (auto-generated by sprite-system)
// DO NOT EDIT BY HAND. Regenerate via:
//   cd sprite-system && python3 lingua_sprites.py    then POST /api/manifest
// ═══════════════════════════════════════════════════════════════════

export const LANG_SPRITE: Record<string, string> = {
  "en": "/sprites/language/lang-en.png",
  "ar": "/sprites/language/lang-ar.png",
  "bg": "/sprites/language/lang-bg.png",
  "zh": "/sprites/language/lang-zh.png",
  "nl": "/sprites/language/lang-nl.png",
  "tl": "/sprites/language/lang-tl.png",
  "fr": "/sprites/language/lang-fr.png",
  "de": "/sprites/language/lang-de.png",
  "hi": "/sprites/language/lang-hi.png",
  "id": "/sprites/language/lang-id.png",
  "it": "/sprites/language/lang-it.png",
  "ja": "/sprites/language/lang-ja.png",
  "ko": "/sprites/language/lang-ko.png",
  "pl": "/sprites/language/lang-pl.png",
  "pt": "/sprites/language/lang-pt.png",
  "ru": "/sprites/language/lang-ru.png",
  "es": "/sprites/language/lang-es.png",
  "sv": "/sprites/language/lang-sv.png",
  "th": "/sprites/language/lang-th.png",
  "tr": "/sprites/language/lang-tr.png",
  "vi": "/sprites/language/lang-vi.png",
};

export const SCENE_SPRITE: Record<string, string> = {
  "social": "/sprites/scene/scene-social.png",
  "food": "/sprites/scene/scene-food.png",
  "compliment": "/sprites/scene/scene-compliment.png",
  "navigate": "/sprites/scene/scene-navigate.png",
  "formal": "/sprites/scene/scene-formal.png",
  "custom": "/sprites/scene/scene-custom.png",
};

export const UTILITY_SPRITE: Record<string, string> = {
  "favorite": "/sprites/utility/utility-favorite.png",
  "saved": "/sprites/utility/utility-saved.png",
  "recent": "/sprites/utility/utility-recent.png",
  "quiz": "/sprites/utility/utility-quiz.png",
  "home": "/sprites/utility/utility-home.png",
  "compose": "/sprites/utility/utility-compose.png",
  "push": "/sprites/utility/utility-push.png",
  "search": "/sprites/utility/utility-search.png",
};

/** Scene category ordering used by the app UI. */
export const SCENE_ORDER: ReadonlyArray<string> = [
  "social",
  "food",
  "compliment",
  "navigate",
  "formal",
  "custom",
];
